-- Durable official FPL season history, matched to Draft players by stable code.

create table if not exists public.player_season_stats (
  id bigint generated by default as identity primary key,
  player_code integer not null,
  current_player_id integer references public.players(id) on delete set null,
  standard_fpl_element_id integer,
  season_name text not null,
  start_cost integer,
  end_cost integer,
  total_points integer not null default 0,
  minutes integer not null default 0,
  starts integer not null default 0,
  goals_scored integer not null default 0,
  assists integer not null default 0,
  clean_sheets integer not null default 0,
  goals_conceded integer not null default 0,
  own_goals integer not null default 0,
  penalties_saved integer not null default 0,
  penalties_missed integer not null default 0,
  yellow_cards integer not null default 0,
  red_cards integer not null default 0,
  saves integer not null default 0,
  bonus integer not null default 0,
  bps integer not null default 0,
  influence numeric not null default 0,
  creativity numeric not null default 0,
  threat numeric not null default 0,
  ict_index numeric not null default 0,
  clearances_blocks_interceptions integer not null default 0,
  recoveries integer not null default 0,
  tackles integer not null default 0,
  defensive_contribution integer not null default 0,
  expected_goals numeric not null default 0,
  expected_assists numeric not null default 0,
  expected_goal_involvements numeric not null default 0,
  expected_goals_conceded numeric not null default 0,
  source_synced_at timestamptz not null default now(),
  unique (player_code, season_name)
);

create index if not exists player_season_stats_current_player_idx
  on public.player_season_stats(current_player_id, season_name);

alter table public.player_season_stats enable row level security;

drop policy if exists "Authenticated managers can view player season history"
  on public.player_season_stats;
create policy "Authenticated managers can view player season history"
  on public.player_season_stats for select to authenticated
  using (true);

revoke insert, update, delete on public.player_season_stats
  from public, anon, authenticated;
grant select on public.player_season_stats to authenticated, service_role;
grant insert, update, delete on public.player_season_stats to service_role;

comment on table public.player_season_stats is
  'Official aggregate FPL history by stable player code and season. Match-by-match custom DEFCON tier points cannot be reconstructed from these aggregates.';

-- Start an import without exposing the shared Edge Function secret to clients.
-- The Edge Function derives the previous season label from the current date.
create or replace function public.trigger_player_season_history_sync()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cron_secret text;
  v_request_id bigint;
begin
  select secret.decrypted_secret into v_cron_secret
  from vault.decrypted_secrets secret
  where secret.name = 'live_stats_cron_secret'
  limit 1;

  if v_cron_secret is null then
    raise exception 'live_stats_cron_secret is not configured';
  end if;

  select net.http_get(
    url := 'https://fnysbiwhwcqqqdwvhkau.supabase.co/functions/v1/sync-live-stats?mode=history',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', v_cron_secret
    ),
    timeout_milliseconds := 120000
  ) into v_request_id;

  return v_request_id;
end;
$$;

revoke all on function public.trigger_player_season_history_sync() from public, anon, authenticated;
grant execute on function public.trigger_player_season_history_sync() to service_role;
