-- Atomic in-season lineup management.
-- A manager submits the entire XI and ordered bench. The database validates
-- ownership and formation before changing a single roster row.

create table if not exists public.lineup_change_audit (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  user_id uuid not null,
  gameweek integer,
  starting_player_ids integer[] not null,
  bench_player_ids integer[] not null,
  previous_starting_player_ids integer[] not null,
  previous_bench_player_ids integer[] not null,
  created_at timestamptz not null default pg_catalog.now(),
  foreign key (league_id, user_id)
    references public.league_members(league_id, user_id)
    on delete cascade
);

create index if not exists lineup_change_audit_manager_idx
  on public.lineup_change_audit(league_id, user_id, created_at desc);

alter table public.lineup_change_audit enable row level security;

drop policy if exists "Managers can view their lineup changes" on public.lineup_change_audit;
create policy "Managers can view their lineup changes"
  on public.lineup_change_audit
  for select
  to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.leagues l
      where l.id = lineup_change_audit.league_id
        and l.commissioner_id = auth.uid()
    )
  );

create or replace function public.save_manager_lineup(
  p_league_id uuid,
  p_starting_player_ids integer[],
  p_bench_player_ids integer[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_roster_count integer;
  v_submitted_count integer;
  v_distinct_count integer;
  v_starter_gkp integer;
  v_starter_def integer;
  v_starter_mid integer;
  v_starter_fwd integer;
  v_bench_gkp integer;
  v_gameweek integer;
  v_previous_starters integer[];
  v_previous_bench integer[];
begin
  if v_user_id is null then
    return jsonb_build_object('success', false, 'error', 'AUTH_REQUIRED');
  end if;

  if not exists (
    select 1 from public.league_members lm
    where lm.league_id = p_league_id and lm.user_id = v_user_id
  ) then
    return jsonb_build_object('success', false, 'error', 'NOT_LEAGUE_MEMBER');
  end if;

  if cardinality(coalesce(p_starting_player_ids, array[]::integer[])) <> 11 then
    return jsonb_build_object('success', false, 'error', 'STARTING_XI_REQUIRES_11');
  end if;
  if cardinality(coalesce(p_bench_player_ids, array[]::integer[])) <> 4 then
    return jsonb_build_object('success', false, 'error', 'BENCH_REQUIRES_4');
  end if;

  perform 1
  from public.rosters r
  where r.league_id = p_league_id and r.user_id = v_user_id
  for update;

  select count(*) into v_roster_count
  from public.rosters r
  where r.league_id = p_league_id and r.user_id = v_user_id;

  select count(*), count(distinct player_id)
  into v_submitted_count, v_distinct_count
  from unnest(p_starting_player_ids || p_bench_player_ids) submitted(player_id);

  if v_roster_count <> 15
     or v_submitted_count <> 15
     or v_distinct_count <> 15
     or exists (
       select 1
       from unnest(p_starting_player_ids || p_bench_player_ids) submitted(player_id)
       where not exists (
         select 1 from public.rosters r
         where r.league_id = p_league_id
           and r.user_id = v_user_id
           and r.player_id = submitted.player_id
       )
     ) then
    return jsonb_build_object('success', false, 'error', 'ROSTER_MISMATCH');
  end if;

  with effective_positions as (
    select submitted.player_id,
      upper(p.element_type::text) as position
    from unnest(p_starting_player_ids) submitted(player_id)
    join public.players p on p.id = submitted.player_id
  )
  select
    count(*) filter (where position in ('GKP', '1')),
    count(*) filter (where position in ('DEF', '2')),
    count(*) filter (where position in ('MID', '3')),
    count(*) filter (where position in ('FWD', '4'))
  into v_starter_gkp, v_starter_def, v_starter_mid, v_starter_fwd
  from effective_positions;

  if v_starter_gkp <> 1
     or v_starter_def not between 3 and 5
     or v_starter_mid not between 2 and 5
     or v_starter_fwd not between 1 and 3 then
    return jsonb_build_object(
      'success', false,
      'error', 'INVALID_FORMATION',
      'formation', jsonb_build_object(
        'GKP', v_starter_gkp, 'DEF', v_starter_def,
        'MID', v_starter_mid, 'FWD', v_starter_fwd
      )
    );
  end if;

  select count(*) into v_bench_gkp
  from unnest(p_bench_player_ids) submitted(player_id)
  join public.players p on p.id = submitted.player_id
  where upper(p.element_type::text) in ('GKP', '1');

  if v_bench_gkp <> 1 then
    return jsonb_build_object('success', false, 'error', 'BENCH_REQUIRES_ONE_GKP');
  end if;

  select
    coalesce(array_agg(r.player_id order by r.player_id) filter (where r.is_starting), array[]::integer[]),
    coalesce(array_agg(r.player_id order by r.bench_order, r.player_id) filter (where not r.is_starting), array[]::integer[])
  into v_previous_starters, v_previous_bench
  from public.rosters r
  where r.league_id = p_league_id and r.user_id = v_user_id;

  update public.rosters r
  set is_starting = true,
      is_starter = true,
      bench_order = null
  where r.league_id = p_league_id
    and r.user_id = v_user_id
    and r.player_id = any(p_starting_player_ids);

  with ordered_bench as (
    select submitted.player_id, submitted.ordinality,
      upper(p.element_type::text) as position
    from unnest(p_bench_player_ids) with ordinality submitted(player_id, ordinality)
    join public.players p on p.id = submitted.player_id
  ), ranked_bench as (
    select player_id, position,
      sum(case when position not in ('GKP', '1') then 1 else 0 end)
        over (order by ordinality) as outfield_order
    from ordered_bench
  )
  update public.rosters r
  set is_starting = false,
      is_starter = false,
      bench_order = case
        when ranked_bench.position in ('GKP', '1') then 0
        else ranked_bench.outfield_order
      end
  from ranked_bench
  where r.league_id = p_league_id
    and r.user_id = v_user_id
    and r.player_id = ranked_bench.player_id;

  select g.gameweek into v_gameweek
  from public.league_gameweeks g
  where g.league_id = p_league_id and coalesce(g.is_current, false)
  order by g.gameweek desc limit 1;

  insert into public.lineup_change_audit (
    league_id, user_id, gameweek, starting_player_ids, bench_player_ids,
    previous_starting_player_ids, previous_bench_player_ids
  ) values (
    p_league_id, v_user_id, v_gameweek, p_starting_player_ids,
    p_bench_player_ids, v_previous_starters, v_previous_bench
  );

  return jsonb_build_object(
    'success', true,
    'gameweek', v_gameweek,
    'formation', jsonb_build_object(
      'GKP', v_starter_gkp, 'DEF', v_starter_def,
      'MID', v_starter_mid, 'FWD', v_starter_fwd
    ),
    'bench_player_ids', to_jsonb(p_bench_player_ids)
  );
end;
$$;

revoke all on function public.save_manager_lineup(uuid, integer[], integer[])
  from public, anon;
grant execute on function public.save_manager_lineup(uuid, integer[], integer[])
  to authenticated;

grant select on public.lineup_change_audit to authenticated;

comment on function public.save_manager_lineup(uuid, integer[], integer[]) is
  'Atomically validates and saves a manager starting XI plus GK/outfield substitute priority.';
