create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  announcements_enabled boolean not null default true,
  trades_enabled boolean not null default true,
  waivers_enabled boolean not null default true,
  match_updates_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  league_id uuid references public.leagues(id) on delete cascade,
  category text not null check (category in ('ANNOUNCEMENT', 'TRADE', 'WAIVER', 'MATCH', 'SYSTEM')),
  title text not null,
  body text not null,
  route text,
  dedupe_key text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists user_notifications_dedupe_idx
  on public.user_notifications (user_id, dedupe_key)
  where dedupe_key is not null;

create index if not exists user_notifications_inbox_idx
  on public.user_notifications (user_id, read_at, created_at desc);

alter table public.notification_preferences enable row level security;
alter table public.user_notifications enable row level security;

drop policy if exists "Managers control their notification preferences" on public.notification_preferences;
create policy "Managers control their notification preferences"
  on public.notification_preferences for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Managers can read their notifications" on public.user_notifications;
create policy "Managers can read their notifications"
  on public.user_notifications for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Managers can update their notifications" on public.user_notifications;
create policy "Managers can update their notifications"
  on public.user_notifications for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Managers can remove their notifications" on public.user_notifications;
create policy "Managers can remove their notifications"
  on public.user_notifications for delete
  to authenticated
  using (auth.uid() = user_id);

revoke all on table public.notification_preferences from public, anon;
revoke all on table public.user_notifications from public, anon;
grant select, insert, update on table public.notification_preferences to authenticated;
grant select, update, delete on table public.user_notifications to authenticated;

create or replace function public.notify_league_announcement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_notifications (
    user_id, league_id, category, title, body, route, dedupe_key
  )
  select
    member.user_id,
    new.league_id,
    'ANNOUNCEMENT',
    case when new.priority = 'URGENT' then 'Urgent league announcement' else 'League announcement' end,
    new.title,
    '/notifications',
    'announcement:' || new.id::text
  from public.league_members member
  left join public.notification_preferences preference on preference.user_id = member.user_id
  where member.league_id = new.league_id
    and member.user_id <> new.author_id
    and coalesce(preference.announcements_enabled, true)
  on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  return new;
end;
$$;

drop trigger if exists league_announcement_notification on public.league_announcements;
create trigger league_announcement_notification
  after insert on public.league_announcements
  for each row execute function public.notify_league_announcement();

create or replace function public.notify_trade_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text := upper(new.status::text);
  v_type text := upper(new.type::text);
  v_package_key text := coalesce(new.parent_transaction_id::text, new.id::text);
  v_target uuid;
  v_title text;
  v_body text;
begin
  if v_type <> 'TRADE' then return new; end if;

  if tg_op = 'INSERT' and v_status = 'PENDING' and new.receiver_id is not null then
    v_target := new.receiver_id;
    v_title := 'New trade offer';
    v_body := 'A manager has sent you a trade offer.';
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status
    and v_status in ('ACCEPTED', 'REJECTED', 'COUNTERED', 'CANCELLED') then
    v_target := new.sender_id;
    v_title := 'Trade offer ' || lower(v_status);
    v_body := 'One of your trade offers has been ' || lower(v_status) || '.';
  else
    return new;
  end if;

  if v_target is null or not coalesce((select trades_enabled from public.notification_preferences where user_id = v_target), true) then
    return new;
  end if;

  insert into public.user_notifications (
    user_id, league_id, category, title, body, route, dedupe_key
  ) values (
    v_target,
    new.league_id,
    'TRADE',
    v_title,
    v_body,
    '/(tabs)/market/waivers-trades?tab=OFFERS',
    'trade:' || v_package_key || ':' || v_status
  )
  on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  return new;
end;
$$;

drop trigger if exists transaction_notification on public.transactions;
create trigger transaction_notification
  after insert or update of status on public.transactions
  for each row execute function public.notify_trade_activity();

create or replace function public.notify_waiver_outcome()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text := upper(new.status::text);
  v_player_name text;
begin
  if new.status is not distinct from old.status or v_status = 'PENDING' then return new; end if;
  if not coalesce((select waivers_enabled from public.notification_preferences where user_id = new.user_id), true) then return new; end if;

  select web_name into v_player_name from public.players where id = new.player_to_add;

  insert into public.user_notifications (
    user_id, league_id, category, title, body, route, dedupe_key
  ) values (
    new.user_id,
    new.league_id,
    'WAIVER',
    case when v_status in ('SUCCESSFUL', 'PROCESSED', 'COMPLETED') then 'Waiver successful' else 'Waiver unsuccessful' end,
    case
      when v_status in ('SUCCESSFUL', 'PROCESSED', 'COMPLETED') then coalesce(v_player_name, 'Your selected player') || ' has joined your squad.'
      else 'Your claim for ' || coalesce(v_player_name, 'the selected player') || ' was not successful.'
    end,
    '/(tabs)/market/waiver-history',
    'waiver:' || new.id::text || ':' || v_status
  )
  on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  return new;
end;
$$;

drop trigger if exists waiver_outcome_notification on public.waiver_claims;
create trigger waiver_outcome_notification
  after update of status on public.waiver_claims
  for each row execute function public.notify_waiver_outcome();
