-- Deduplicated, league-aware live scoring events and manager/opponent alerts.

alter table public.notification_preferences
  add column if not exists own_player_events_enabled boolean not null default true,
  add column if not exists opponent_player_events_enabled boolean not null default true;

create table if not exists public.live_player_events (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  gameweek integer not null check (gameweek between 1 and 38),
  player_id integer not null references public.players(id) on delete cascade,
  event_type text not null check (event_type in ('GOAL', 'ASSIST', 'SAVE_POINT', 'DEFCON')),
  event_level integer not null,
  source_value integer not null,
  points_value integer not null,
  created_at timestamptz not null default pg_catalog.now(),
  unique (league_id, gameweek, player_id, event_type, event_level)
);

create index if not exists live_player_events_lookup_idx
  on public.live_player_events(league_id, gameweek, created_at desc);

alter table public.live_player_events enable row level security;
revoke all on public.live_player_events from public, anon, authenticated;
grant all on public.live_player_events to service_role;

create or replace function public.queue_live_player_event(
  p_league_id uuid,
  p_gameweek integer,
  p_player_id integer,
  p_owner_id uuid,
  p_is_starting boolean,
  p_event_type text,
  p_event_level integer,
  p_source_value integer,
  p_points_value integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_id bigint;
  v_player_name text;
  v_owner_team text;
  v_fixture_id uuid;
  v_opponent_id uuid;
  v_action_text text;
  v_title text;
begin
  insert into public.live_player_events (
    league_id, gameweek, player_id, event_type, event_level, source_value, points_value
  ) values (
    p_league_id, p_gameweek, p_player_id, p_event_type, p_event_level, p_source_value, p_points_value
  )
  on conflict (league_id, gameweek, player_id, event_type, event_level) do nothing
  returning id into v_event_id;

  if v_event_id is null then return; end if;

  select coalesce(player.web_name, player.second_name, 'Your player')
  into v_player_name
  from public.players player
  where player.id = p_player_id;

  select coalesce(member.team_name, 'your opponent')
  into v_owner_team
  from public.league_members member
  where member.league_id = p_league_id and member.user_id = p_owner_id;

  select
    fixture.id,
    case
      when fixture.home_user_id = p_owner_id then fixture.away_user_id
      else fixture.home_user_id
    end
  into v_fixture_id, v_opponent_id
  from public.league_fixtures fixture
  where fixture.league_id = p_league_id
    and fixture.gameweek = p_gameweek
    and p_owner_id in (fixture.home_user_id, fixture.away_user_id)
  limit 1;

  case p_event_type
    when 'GOAL' then
      v_title := 'Goal — ' || v_player_name;
      v_action_text := 'has scored. +' || p_points_value || ' points';
    when 'ASSIST' then
      v_title := 'Assist — ' || v_player_name;
      v_action_text := 'has registered an assist. +3 points';
    when 'SAVE_POINT' then
      v_title := 'Save point — ' || v_player_name;
      v_action_text := 'has made ' || p_source_value || ' saves and reached +' || p_points_value || ' save points';
    when 'DEFCON' then
      v_title := 'DEFCON reached — ' || v_player_name;
      v_action_text := 'has reached a custom DEFCON tier worth +' || p_points_value || ' points';
    else
      return;
  end case;

  insert into public.user_notifications (
    user_id, league_id, category, title, body, route, dedupe_key
  )
  select
    p_owner_id,
    p_league_id,
    'MATCH',
    v_title,
    v_player_name || ' ' || v_action_text || case when p_is_starting then ' for your XI.' else ' on your bench.' end,
    '/(tabs)/league/matches?gameweek=' || p_gameweek::text || coalesce('&fixtureId=' || v_fixture_id::text, ''),
    'live-event:' || v_event_id::text || ':own'
  where coalesce((
    select preference.match_updates_enabled and preference.own_player_events_enabled
    from public.notification_preferences preference
    where preference.user_id = p_owner_id
  ), true)
  on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;

  if p_is_starting and v_opponent_id is not null then
    insert into public.user_notifications (
      user_id, league_id, category, title, body, route, dedupe_key
    )
    select
      v_opponent_id,
      p_league_id,
      'MATCH',
      case p_event_type
        when 'GOAL' then 'Opponent goal — ' || v_player_name
        when 'ASSIST' then 'Opponent assist — ' || v_player_name
        when 'SAVE_POINT' then 'Opponent save point — ' || v_player_name
        else 'Opponent DEFCON — ' || v_player_name
      end,
      v_player_name || ' ' || v_action_text || ' for ' || v_owner_team || ', your GW' || p_gameweek::text || ' opponent.',
      '/(tabs)/league/matches?gameweek=' || p_gameweek::text || coalesce('&fixtureId=' || v_fixture_id::text, ''),
      'live-event:' || v_event_id::text || ':opponent'
    where coalesce((
      select preference.match_updates_enabled and preference.opponent_player_events_enabled
      from public.notification_preferences preference
      where preference.user_id = v_opponent_id
    ), true)
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  end if;
end;
$$;

create or replace function public.detect_live_player_events()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_goals integer := case when tg_op = 'UPDATE' then coalesce(old.goals_scored, 0) else 0 end;
  v_old_assists integer := case when tg_op = 'UPDATE' then coalesce(old.assists, 0) else 0 end;
  v_old_saves integer := case when tg_op = 'UPDATE' then coalesce(old.saves, 0) else 0 end;
  v_old_defcon_actions integer := case when tg_op = 'UPDATE' then coalesce(old.defensive_contribution, 0) else 0 end;
  v_player_position text;
  v_goal_points integer;
  v_old_defcon_points integer;
  v_new_defcon_points integer;
  v_level integer;
  v_snapshot record;
begin
  if coalesce(new.goals_scored, 0) <= v_old_goals
     and coalesce(new.assists, 0) <= v_old_assists
     and coalesce(new.saves, 0) / 3 <= v_old_saves / 3
     and coalesce(new.defensive_contribution, 0) <= v_old_defcon_actions then
    return new;
  end if;

  select upper(coalesce(player.element_type::text, 'FWD'))
  into v_player_position
  from public.players player where player.id = new.player_id;

  v_goal_points := case
    when v_player_position in ('1', 'GKP', 'GK', '2', 'DEF') then 6
    when v_player_position in ('3', 'MID') then 5
    else 4
  end;

  for v_snapshot in
    select
      snapshot.league_id,
      snapshot.user_id,
      new.player_id = any(snapshot.effective_starting_player_ids) as is_starting
    from public.gameweek_lineup_snapshots snapshot
    join public.league_gameweeks league_gameweek
      on league_gameweek.league_id = snapshot.league_id
     and league_gameweek.gameweek = snapshot.gameweek
    where snapshot.gameweek = new.gameweek
      and (
        new.player_id = any(snapshot.effective_starting_player_ids)
        or new.player_id = any(snapshot.effective_bench_player_ids)
      )
      and league_gameweek.gw_deadline <= pg_catalog.now()
      and not coalesce(league_gameweek.is_finished, false)
      and not exists (
        select 1 from public.gameweek_simulation_runs simulation
        where simulation.league_id = snapshot.league_id
          and simulation.status = 'ACTIVE'
          and simulation.expires_at > pg_catalog.now()
      )
  loop
    if coalesce(new.goals_scored, 0) > v_old_goals then
      for v_level in (v_old_goals + 1)..coalesce(new.goals_scored, 0) loop
        perform public.queue_live_player_event(v_snapshot.league_id, new.gameweek, new.player_id, v_snapshot.user_id, v_snapshot.is_starting, 'GOAL', v_level, v_level, v_goal_points);
      end loop;
    end if;

    if coalesce(new.assists, 0) > v_old_assists then
      for v_level in (v_old_assists + 1)..coalesce(new.assists, 0) loop
        perform public.queue_live_player_event(v_snapshot.league_id, new.gameweek, new.player_id, v_snapshot.user_id, v_snapshot.is_starting, 'ASSIST', v_level, v_level, 3);
      end loop;
    end if;

    if coalesce(new.saves, 0) / 3 > v_old_saves / 3 then
      for v_level in (v_old_saves / 3 + 1)..(coalesce(new.saves, 0) / 3) loop
        perform public.queue_live_player_event(v_snapshot.league_id, new.gameweek, new.player_id, v_snapshot.user_id, v_snapshot.is_starting, 'SAVE_POINT', v_level, v_level * 3, v_level);
      end loop;
    end if;

    if coalesce(new.defensive_contribution, 0) > v_old_defcon_actions
       and v_player_position not in ('1', 'GKP', 'GK') then
      v_old_defcon_points := public.calculate_player_defcon_points(v_snapshot.league_id, v_player_position, v_old_defcon_actions);
      v_new_defcon_points := public.calculate_player_defcon_points(v_snapshot.league_id, v_player_position, coalesce(new.defensive_contribution, 0));
      if v_new_defcon_points > v_old_defcon_points then
        perform public.queue_live_player_event(v_snapshot.league_id, new.gameweek, new.player_id, v_snapshot.user_id, v_snapshot.is_starting, 'DEFCON', v_new_defcon_points, coalesce(new.defensive_contribution, 0), v_new_defcon_points);
      end if;
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists live_player_event_detection on public.player_gameweek_stats;
create trigger live_player_event_detection
after insert or update of goals_scored, assists, saves, defensive_contribution
on public.player_gameweek_stats
for each row execute function public.detect_live_player_events();

revoke all on function public.queue_live_player_event(uuid,integer,integer,uuid,boolean,text,integer,integer,integer) from public, anon, authenticated;
revoke all on function public.detect_live_player_events() from public, anon, authenticated;

comment on table public.live_player_events is
  'Deduplicated live goal, assist, save-point and custom DEFCON threshold events used to notify locked-lineup owners and opponents.';

