-- Commissioner-only, reversible Gameweek rehearsal harness.
-- Only one run may be active because FPL Gameweek state and player statistics
-- are shared across every league in the project.

create table if not exists public.gameweek_simulation_config (
  singleton boolean primary key default true check (singleton),
  enabled boolean not null default false,
  enabled_until timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.gameweek_simulation_config (singleton, enabled, enabled_until)
values (true, true, now() + interval '30 days')
on conflict (singleton) do update
set enabled = true,
    enabled_until = greatest(public.gameweek_simulation_config.enabled_until, excluded.enabled_until),
    updated_at = now();

create table if not exists public.gameweek_simulation_runs (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  gameweek integer not null check (gameweek between 1 and 38),
  commissioner_id uuid not null references auth.users(id),
  phase text not null default 'PRE_DEADLINE' check (
    phase in ('PRE_DEADLINE', 'LOCKED', 'LIVE', 'FINISHED', 'AUTOSUBS', 'WAIVERS_OPEN')
  ),
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'RESET', 'EXPIRED')),
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '4 hours',
  ended_at timestamptz,
  end_reason text,
  gameweeks_backup jsonb not null,
  player_stats_backup jsonb not null,
  league_gameweeks_backup jsonb not null,
  fixtures_backup jsonb not null,
  rosters_backup jsonb not null,
  snapshots_backup jsonb not null,
  autosub_audit_backup jsonb not null,
  waiver_claims_backup jsonb not null,
  waiver_locks_backup jsonb not null,
  free_agents_backup jsonb not null,
  transactions_backup jsonb not null
);

create unique index if not exists one_active_gameweek_simulation_idx
  on public.gameweek_simulation_runs ((status)) where status = 'ACTIVE';

create table if not exists public.gameweek_simulation_audit (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.gameweek_simulation_runs(id) on delete cascade,
  actor_id uuid references auth.users(id),
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.gameweek_simulation_config enable row level security;
alter table public.gameweek_simulation_runs enable row level security;
alter table public.gameweek_simulation_audit enable row level security;
revoke all on public.gameweek_simulation_config, public.gameweek_simulation_runs,
  public.gameweek_simulation_audit from public, anon, authenticated;

create or replace function public.restore_gameweek_simulation_internal(
  p_run_id uuid,
  p_reason text default 'RESET'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run public.gameweek_simulation_runs%rowtype;
  v_final_status text;
begin
  select * into v_run
  from public.gameweek_simulation_runs run
  where run.id = p_run_id
  for update;

  if not found then
    return jsonb_build_object('success', false, 'error', 'RUN_NOT_FOUND');
  end if;
  if v_run.status <> 'ACTIVE' then
    return jsonb_build_object('success', true, 'already_restored', true, 'status', v_run.status);
  end if;

  delete from public.gameweek_autosub_audit where league_id = v_run.league_id;
  delete from public.gameweek_lineup_snapshots where league_id = v_run.league_id;
  delete from public.waiver_claims where league_id = v_run.league_id;
  delete from public.waiver_player_locks where league_id = v_run.league_id;
  delete from public.free_agent_transactions where league_id = v_run.league_id;
  delete from public.transactions where league_id = v_run.league_id;
  delete from public.rosters where league_id = v_run.league_id;
  delete from public.league_fixtures where league_id = v_run.league_id;
  delete from public.league_gameweeks where league_id = v_run.league_id;
  delete from public.player_gameweek_stats where gameweek = v_run.gameweek;

  insert into public.player_gameweek_stats
  select * from jsonb_populate_recordset(null::public.player_gameweek_stats, v_run.player_stats_backup);
  insert into public.league_gameweeks
  select * from jsonb_populate_recordset(null::public.league_gameweeks, v_run.league_gameweeks_backup);
  insert into public.league_fixtures
  select * from jsonb_populate_recordset(null::public.league_fixtures, v_run.fixtures_backup);
  insert into public.rosters
  select * from jsonb_populate_recordset(null::public.rosters, v_run.rosters_backup);
  insert into public.gameweek_lineup_snapshots
  select * from jsonb_populate_recordset(null::public.gameweek_lineup_snapshots, v_run.snapshots_backup);
  insert into public.gameweek_autosub_audit overriding system value
  select * from jsonb_populate_recordset(null::public.gameweek_autosub_audit, v_run.autosub_audit_backup);
  insert into public.waiver_claims
  select * from jsonb_populate_recordset(null::public.waiver_claims, v_run.waiver_claims_backup);
  insert into public.waiver_player_locks
  select * from jsonb_populate_recordset(null::public.waiver_player_locks, v_run.waiver_locks_backup);
  insert into public.free_agent_transactions
  select * from jsonb_populate_recordset(null::public.free_agent_transactions, v_run.free_agents_backup);
  insert into public.transactions
  select restored.*
  from jsonb_populate_recordset(null::public.transactions, v_run.transactions_backup) restored
  where restored.parent_transaction_id is null;
  insert into public.transactions
  select restored.*
  from jsonb_populate_recordset(null::public.transactions, v_run.transactions_backup) restored
  where restored.parent_transaction_id is not null;

  update public.gameweeks target
  set fpl_deadline_time = restored.fpl_deadline_time,
      is_current = restored.is_current,
      is_finished = restored.is_finished
  from jsonb_populate_recordset(null::public.gameweeks, v_run.gameweeks_backup) restored
  where target.gameweek_number = restored.gameweek_number;

  v_final_status := case when upper(coalesce(p_reason, 'RESET')) = 'EXPIRED' then 'EXPIRED' else 'RESET' end;
  update public.gameweek_simulation_runs
  set status = v_final_status,
      ended_at = now(),
      updated_at = now(),
      end_reason = left(coalesce(p_reason, v_final_status), 240)
  where id = v_run.id;

  insert into public.gameweek_simulation_audit(run_id, actor_id, action, details)
  values (v_run.id, auth.uid(), v_final_status, jsonb_build_object('reason', p_reason));

  return jsonb_build_object('success', true, 'status', v_final_status, 'run_id', v_run.id);
end;
$$;

create or replace function public.expire_gameweek_simulations()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run record;
  v_count integer := 0;
begin
  for v_run in
    select id from public.gameweek_simulation_runs
    where status = 'ACTIVE' and expires_at <= now()
    order by expires_at
  loop
    perform public.restore_gameweek_simulation_internal(v_run.id, 'EXPIRED');
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object('success', true, 'expired_runs_restored', v_count);
end;
$$;

create or replace function public.get_gameweek_simulation_status(p_league_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_enabled boolean := false;
  v_commissioner boolean := false;
  v_member boolean := false;
  v_run jsonb;
  v_gameweeks jsonb;
begin
  select coalesce(config.enabled, false)
         and (config.enabled_until is null or config.enabled_until > now())
  into v_enabled
  from public.gameweek_simulation_config config where config.singleton;

  select exists (
    select 1 from public.leagues league
    where league.id = p_league_id and league.commissioner_id = auth.uid()
  ) into v_commissioner;

  select exists (
    select 1 from public.league_members member
    where member.league_id = p_league_id and member.user_id = auth.uid()
  ) into v_member;

  if not v_member then
    return jsonb_build_object('enabled', false, 'is_commissioner', false, 'error', 'LEAGUE_MEMBER_REQUIRED');
  end if;

  select to_jsonb(run) - array[
    'gameweeks_backup','player_stats_backup','league_gameweeks_backup','fixtures_backup',
    'rosters_backup','snapshots_backup','autosub_audit_backup','waiver_claims_backup',
    'waiver_locks_backup','free_agents_backup','transactions_backup'
  ]::text[]
  into v_run
  from public.gameweek_simulation_runs run
  where run.status = 'ACTIVE'
  order by run.started_at desc limit 1;

  select coalesce(jsonb_agg(jsonb_build_object(
    'gameweek', gameweek.gameweek_number,
    'deadline', gameweek.fpl_deadline_time,
    'is_current', coalesce(gameweek.is_current, false),
    'is_finished', coalesce(gameweek.is_finished, false)
  ) order by gameweek.gameweek_number), '[]'::jsonb)
  into v_gameweeks from public.gameweeks gameweek;

  return jsonb_build_object(
    'enabled', v_enabled,
    'is_commissioner', v_commissioner,
    'active_run', v_run,
    'live_sync_paused', v_run is not null,
    'available_gameweeks', v_gameweeks
  );
end;
$$;

create or replace function public.start_gameweek_simulation(
  p_league_id uuid,
  p_gameweek integer,
  p_duration_minutes integer default 240
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run_id uuid;
  v_member_count integer;
  v_valid_rosters integer;
  v_enabled boolean;
begin
  perform public.expire_gameweek_simulations();

  select coalesce(config.enabled, false)
         and (config.enabled_until is null or config.enabled_until > now())
  into v_enabled from public.gameweek_simulation_config config where config.singleton;
  if not coalesce(v_enabled, false) then
    return jsonb_build_object('success', false, 'error', 'SIMULATION_DISABLED');
  end if;
  if not exists (select 1 from public.leagues league where league.id = p_league_id and league.commissioner_id = auth.uid()) then
    return jsonb_build_object('success', false, 'error', 'COMMISSIONER_REQUIRED');
  end if;
  if p_gameweek not between 1 and 38 or not exists (
    select 1 from public.gameweeks gameweek where gameweek.gameweek_number = p_gameweek
  ) then
    return jsonb_build_object('success', false, 'error', 'INVALID_GAMEWEEK');
  end if;
  if exists (select 1 from public.gameweek_simulation_runs where status = 'ACTIVE') then
    return jsonb_build_object('success', false, 'error', 'ANOTHER_SIMULATION_IS_ACTIVE');
  end if;

  select count(*) into v_member_count from public.league_members member where member.league_id = p_league_id;
  select count(*) into v_valid_rosters
  from (
    select roster.user_id from public.rosters roster
    where roster.league_id = p_league_id
    group by roster.user_id
    having count(*) = 15
       and count(*) filter (where roster.is_starting) = 11
       and count(*) filter (where not roster.is_starting) = 4
  ) valid;
  if v_member_count = 0 or v_valid_rosters <> v_member_count then
    return jsonb_build_object('success', false, 'error', 'EVERY_MANAGER_NEEDS_A_VALID_15_PLAYER_ROSTER');
  end if;
  if not exists (select 1 from public.league_fixtures fixture where fixture.league_id = p_league_id and fixture.gameweek = p_gameweek) then
    return jsonb_build_object('success', false, 'error', 'FIXTURES_REQUIRED');
  end if;

  insert into public.gameweek_simulation_runs (
    league_id, gameweek, commissioner_id, expires_at,
    gameweeks_backup, player_stats_backup, league_gameweeks_backup, fixtures_backup,
    rosters_backup, snapshots_backup, autosub_audit_backup, waiver_claims_backup,
    waiver_locks_backup, free_agents_backup, transactions_backup
  )
  select
    p_league_id, p_gameweek, auth.uid(), now() + make_interval(mins => least(greatest(p_duration_minutes, 30), 480)),
    (select coalesce(jsonb_agg(to_jsonb(g)), '[]'::jsonb) from public.gameweeks g),
    (select coalesce(jsonb_agg(to_jsonb(s)), '[]'::jsonb) from public.player_gameweek_stats s where s.gameweek = p_gameweek),
    (select coalesce(jsonb_agg(to_jsonb(lg)), '[]'::jsonb) from public.league_gameweeks lg where lg.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(f)), '[]'::jsonb) from public.league_fixtures f where f.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(r)), '[]'::jsonb) from public.rosters r where r.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(snap)), '[]'::jsonb) from public.gameweek_lineup_snapshots snap where snap.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(a)), '[]'::jsonb) from public.gameweek_autosub_audit a where a.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(w)), '[]'::jsonb) from public.waiver_claims w where w.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(wl)), '[]'::jsonb) from public.waiver_player_locks wl where wl.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(fa)), '[]'::jsonb) from public.free_agent_transactions fa where fa.league_id = p_league_id),
    (select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) from public.transactions t where t.league_id = p_league_id)
  returning id into v_run_id;

  update public.gameweeks set is_current = false;
  update public.gameweeks
  set is_current = true, is_finished = false, fpl_deadline_time = now() + interval '10 minutes'
  where gameweek_number = p_gameweek;
  update public.league_gameweeks
  set is_current = (gameweek = p_gameweek),
      is_finished = case when gameweek = p_gameweek then false else is_finished end,
      status = case when gameweek = p_gameweek then 'WAIVERS_CLOSED' else status end,
      gw_deadline = case when gameweek = p_gameweek then now() + interval '10 minutes' else gw_deadline end
  where league_id = p_league_id;

  insert into public.gameweek_simulation_audit(run_id, actor_id, action, details)
  values (v_run_id, auth.uid(), 'START', jsonb_build_object('gameweek', p_gameweek, 'members', v_member_count));
  return jsonb_build_object('success', true, 'run_id', v_run_id, 'phase', 'PRE_DEADLINE');
end;
$$;

create or replace function public.advance_gameweek_simulation(p_run_id uuid, p_action text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run public.gameweek_simulation_runs%rowtype;
  v_action text := upper(trim(p_action));
  v_phase text;
  v_result jsonb;
begin
  perform public.expire_gameweek_simulations();
  select * into v_run from public.gameweek_simulation_runs run where run.id = p_run_id for update;
  if not found or v_run.status <> 'ACTIVE' then return jsonb_build_object('success', false, 'error', 'ACTIVE_RUN_NOT_FOUND'); end if;
  if v_run.commissioner_id <> auth.uid() then return jsonb_build_object('success', false, 'error', 'COMMISSIONER_REQUIRED'); end if;

  if v_action = 'LOCK_LINEUPS' and v_run.phase = 'PRE_DEADLINE' then
    update public.gameweeks set fpl_deadline_time = now() - interval '1 minute' where gameweek_number = v_run.gameweek;
    update public.league_gameweeks set gw_deadline = now() - interval '1 minute', status = 'IN_PLAY'
      where league_id = v_run.league_id and gameweek = v_run.gameweek;
    delete from public.gameweek_autosub_audit where league_id = v_run.league_id and gameweek = v_run.gameweek;
    delete from public.gameweek_lineup_snapshots where league_id = v_run.league_id and gameweek = v_run.gameweek;
    insert into public.gameweek_lineup_snapshots (
      league_id, user_id, gameweek, deadline_at, starting_player_ids, bench_player_ids,
      effective_starting_player_ids, effective_bench_player_ids
    )
    select roster.league_id, roster.user_id, v_run.gameweek, now() - interval '1 minute',
      array_agg(roster.player_id order by roster.player_id) filter (where roster.is_starting),
      array_agg(roster.player_id order by roster.bench_order nulls last, roster.player_id) filter (where not roster.is_starting),
      array_agg(roster.player_id order by roster.player_id) filter (where roster.is_starting),
      array_agg(roster.player_id order by roster.bench_order nulls last, roster.player_id) filter (where not roster.is_starting)
    from public.rosters roster where roster.league_id = v_run.league_id
    group by roster.league_id, roster.user_id;
    v_phase := 'LOCKED';
  elsif v_action = 'START_LIVE' and v_run.phase = 'LOCKED' then
    v_phase := 'LIVE';
  elsif v_action = 'FINISH_GAMEWEEK' and v_run.phase = 'LIVE' then
    update public.gameweeks set is_finished = true where gameweek_number = v_run.gameweek;
    update public.league_gameweeks set is_finished = true, status = 'FINISHED'
      where league_id = v_run.league_id and gameweek = v_run.gameweek;
    with scores as (select * from public.get_live_fixture_scores(v_run.gameweek))
    update public.league_fixtures fixture
    set home_score = scores.home_score, home_fpl_points = scores.home_fpl_points,
        home_defcon_points = scores.home_defcon_points, away_score = scores.away_score,
        away_fpl_points = scores.away_fpl_points, away_defcon_points = scores.away_defcon_points,
        is_finished = true
    from scores where fixture.id = scores.fixture_id and fixture.league_id = v_run.league_id;
    v_phase := 'FINISHED';
  elsif v_action = 'PROCESS_AUTOSUBS' and v_run.phase = 'FINISHED' then
    v_result := public.process_gameweek_autosubs(v_run.league_id, v_run.gameweek, true);
    v_phase := 'AUTOSUBS';
  elsif v_action = 'OPEN_NEXT_WAIVER' and v_run.phase = 'AUTOSUBS' then
    update public.league_gameweeks
    set is_current = true, is_finished = false, is_waiver_processed = false,
        status = 'WAIVERS_OPEN', waiver_deadline = now() + interval '5 minutes',
        waiver_deadline_time = now() + interval '5 minutes', waiver_processed_at = null
    where league_id = v_run.league_id and gameweek = v_run.gameweek + 1;
    v_phase := 'WAIVERS_OPEN';
  else
    return jsonb_build_object('success', false, 'error', 'INVALID_PHASE_TRANSITION', 'phase', v_run.phase, 'action', v_action);
  end if;

  update public.gameweek_simulation_runs set phase = v_phase, updated_at = now() where id = v_run.id;
  insert into public.gameweek_simulation_audit(run_id, actor_id, action, details)
  values (v_run.id, auth.uid(), v_action, coalesce(v_result, '{}'::jsonb));
  return jsonb_build_object('success', true, 'run_id', v_run.id, 'phase', v_phase, 'result', v_result);
end;
$$;

create or replace function public.set_gameweek_simulation_player_stats(
  p_run_id uuid,
  p_player_id integer,
  p_preset text default 'CUSTOM',
  p_stats jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run public.gameweek_simulation_runs%rowtype;
  v_position text;
  v_preset text := upper(trim(coalesce(p_preset, 'CUSTOM')));
  v_minutes integer := 0; v_total integer := 0; v_goals integer := 0; v_assists integer := 0;
  v_clean integer := 0; v_conceded integer := 0; v_yellow integer := 0; v_red integer := 0;
  v_saves integer := 0; v_pen_saved integer := 0; v_pen_missed integer := 0; v_own integer := 0;
  v_bonus integer := 0; v_bps integer := 0; v_cbi integer := 0; v_recoveries integer := 0;
  v_tackles integer := 0; v_defcon integer := 0;
begin
  perform public.expire_gameweek_simulations();
  select * into v_run from public.gameweek_simulation_runs run where run.id = p_run_id and run.status = 'ACTIVE';
  if not found then return jsonb_build_object('success', false, 'error', 'ACTIVE_RUN_NOT_FOUND'); end if;
  if v_run.commissioner_id <> auth.uid() then return jsonb_build_object('success', false, 'error', 'COMMISSIONER_REQUIRED'); end if;
  if v_run.phase <> 'LIVE' then return jsonb_build_object('success', false, 'error', 'PLAYER_EVENTS_REQUIRE_LIVE_PHASE'); end if;
  if not exists (select 1 from public.rosters roster where roster.league_id = v_run.league_id and roster.player_id = p_player_id) then
    return jsonb_build_object('success', false, 'error', 'PLAYER_NOT_IN_SIMULATION_LEAGUE');
  end if;
  select upper(player.element_type::text) into v_position from public.players player where player.id = p_player_id;

  if v_preset = 'DID_NOT_PLAY' then null;
  elsif v_preset = 'APPEARANCE' then v_minutes := 90; v_total := 2;
  elsif v_preset = 'GOAL' then
    v_minutes := 90; v_goals := 1;
    v_total := 2 + case when v_position in ('1','GKP','GK','2','DEF') then 6 when v_position in ('3','MID') then 5 else 4 end;
  elsif v_preset = 'ASSIST' then v_minutes := 90; v_assists := 1; v_total := 5;
  elsif v_preset = 'CLEAN_SHEET' then
    v_minutes := 90; v_clean := 1;
    v_total := 2 + case when v_position in ('1','GKP','GK','2','DEF') then 4 when v_position in ('3','MID') then 1 else 0 end;
  elsif v_preset = 'YELLOW_CARD' then v_minutes := 90; v_yellow := 1; v_total := 1;
  elsif v_preset = 'RED_CARD' then v_minutes := 90; v_red := 1; v_total := -1;
  elsif v_preset = 'THREE_SAVES' then v_minutes := 90; v_saves := 3; v_total := 3;
  elsif v_preset = 'CUSTOM' then
    v_minutes := greatest(0, coalesce((p_stats->>'minutes')::integer, 0));
    v_total := coalesce((p_stats->>'total_points')::integer, 0);
    v_goals := greatest(0, coalesce((p_stats->>'goals_scored')::integer, 0));
    v_assists := greatest(0, coalesce((p_stats->>'assists')::integer, 0));
    v_clean := greatest(0, coalesce((p_stats->>'clean_sheets')::integer, 0));
    v_conceded := greatest(0, coalesce((p_stats->>'goals_conceded')::integer, 0));
    v_yellow := greatest(0, coalesce((p_stats->>'yellow_cards')::integer, 0));
    v_red := greatest(0, coalesce((p_stats->>'red_cards')::integer, 0));
    v_saves := greatest(0, coalesce((p_stats->>'saves')::integer, 0));
    v_pen_saved := greatest(0, coalesce((p_stats->>'penalties_saved')::integer, 0));
    v_pen_missed := greatest(0, coalesce((p_stats->>'penalties_missed')::integer, 0));
    v_own := greatest(0, coalesce((p_stats->>'own_goals')::integer, 0));
    v_bonus := greatest(0, coalesce((p_stats->>'bonus')::integer, 0));
    v_bps := coalesce((p_stats->>'bps')::integer, 0);
    v_cbi := greatest(0, coalesce((p_stats->>'clearances_blocks_interceptions')::integer, 0));
    v_recoveries := greatest(0, coalesce((p_stats->>'recoveries')::integer, 0));
    v_tackles := greatest(0, coalesce((p_stats->>'tackles')::integer, 0));
    v_defcon := greatest(0, coalesce((p_stats->>'defensive_contribution')::integer, v_cbi + v_recoveries + v_tackles));
  else return jsonb_build_object('success', false, 'error', 'UNKNOWN_PRESET');
  end if;

  insert into public.player_gameweek_stats (
    player_id, gameweek, minutes, total_points, goals_scored, assists, clean_sheets,
    goals_conceded, yellow_cards, red_cards, saves, penalties_saved, penalties_missed,
    own_goals, bonus, bps, clearances_blocks_interceptions, recoveries, tackles,
    defensive_contribution, updated_at
  ) values (
    p_player_id, v_run.gameweek, v_minutes, v_total, v_goals, v_assists, v_clean,
    v_conceded, v_yellow, v_red, v_saves, v_pen_saved, v_pen_missed, v_own,
    v_bonus, v_bps, v_cbi, v_recoveries, v_tackles, v_defcon, now()
  )
  on conflict (player_id, gameweek) do update set
    minutes=excluded.minutes, total_points=excluded.total_points, goals_scored=excluded.goals_scored,
    assists=excluded.assists, clean_sheets=excluded.clean_sheets, goals_conceded=excluded.goals_conceded,
    yellow_cards=excluded.yellow_cards, red_cards=excluded.red_cards, saves=excluded.saves,
    penalties_saved=excluded.penalties_saved, penalties_missed=excluded.penalties_missed,
    own_goals=excluded.own_goals, bonus=excluded.bonus, bps=excluded.bps,
    clearances_blocks_interceptions=excluded.clearances_blocks_interceptions,
    recoveries=excluded.recoveries, tackles=excluded.tackles,
    defensive_contribution=excluded.defensive_contribution, updated_at=now();

  with scores as (select * from public.get_live_fixture_scores(v_run.gameweek))
  update public.league_fixtures fixture
  set home_score=scores.home_score, home_fpl_points=scores.home_fpl_points,
      home_defcon_points=scores.home_defcon_points, away_score=scores.away_score,
      away_fpl_points=scores.away_fpl_points, away_defcon_points=scores.away_defcon_points
  from scores where fixture.id=scores.fixture_id and fixture.league_id=v_run.league_id;

  insert into public.gameweek_simulation_audit(run_id, actor_id, action, details)
  values (v_run.id, auth.uid(), 'PLAYER_STATS', jsonb_build_object('player_id', p_player_id, 'preset', v_preset, 'total_points', v_total));
  return jsonb_build_object('success', true, 'player_id', p_player_id, 'preset', v_preset, 'minutes', v_minutes, 'total_points', v_total);
exception when invalid_text_representation then
  return jsonb_build_object('success', false, 'error', 'INVALID_NUMBER');
end;
$$;

create or replace function public.get_gameweek_simulation_players(p_run_id uuid)
returns table(
  player_id integer, player_name text, club_name text, "position" text,
  manager_id uuid, manager_name text, is_starting boolean,
  minutes integer, total_points integer, defensive_contribution integer
)
language sql
stable
security definer
set search_path = ''
as $$
  select player.id, coalesce(player.web_name, 'Unknown')::text, coalesce(player.team_name, '')::text,
    upper(player.element_type::text), roster.user_id, coalesce(profile.display_name, 'Manager')::text,
    roster.is_starting, coalesce(stats.minutes, 0)::integer, coalesce(stats.total_points, 0)::integer,
    coalesce(stats.defensive_contribution, 0)::integer
  from public.gameweek_simulation_runs run
  join public.rosters roster on roster.league_id = run.league_id
  join public.players player on player.id = roster.player_id
  left join public.profiles profile on profile.id = roster.user_id
  left join public.player_gameweek_stats stats on stats.player_id = player.id and stats.gameweek = run.gameweek
  where run.id = p_run_id and run.status = 'ACTIVE' and run.commissioner_id = auth.uid()
  order by profile.display_name, roster.is_starting desc, player.element_type, player.web_name;
$$;

create or replace function public.get_gameweek_simulation_integrity(p_run_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_run public.gameweek_simulation_runs%rowtype;
  v_managers integer; v_fixtures integer; v_bad_appearances integer; v_snapshots integer;
  v_invalid_lineups integer; v_score_mismatches integer; v_processed integer;
begin
  select * into v_run from public.gameweek_simulation_runs run where run.id=p_run_id and run.status='ACTIVE';
  if not found or v_run.commissioner_id <> auth.uid() then return jsonb_build_object('success', false, 'error', 'ACTIVE_COMMISSIONER_RUN_REQUIRED'); end if;
  select count(*) into v_managers from public.league_members where league_id=v_run.league_id;
  select count(*) into v_fixtures from public.league_fixtures where league_id=v_run.league_id and gameweek=v_run.gameweek;
  with appearances as (
    select home_user_id user_id from public.league_fixtures where league_id=v_run.league_id and gameweek=v_run.gameweek
    union all select away_user_id from public.league_fixtures where league_id=v_run.league_id and gameweek=v_run.gameweek and away_user_id is not null
  ), counts as (select user_id,count(*) n from appearances group by user_id)
  select count(*) into v_bad_appearances from public.league_members member
  left join counts on counts.user_id=member.user_id
  where member.league_id=v_run.league_id and coalesce(counts.n,0)<>1;
  select count(*), count(*) filter (where not public.is_legal_starting_lineup(effective_starting_player_ids))
  into v_snapshots,v_invalid_lineups from public.gameweek_lineup_snapshots
  where league_id=v_run.league_id and gameweek=v_run.gameweek;
  with live as (select * from public.get_live_fixture_scores(v_run.gameweek))
  select count(*) into v_score_mismatches from public.league_fixtures fixture
  join live on live.fixture_id=fixture.id
  where fixture.league_id=v_run.league_id and (
    coalesce(fixture.home_score,0)<>live.home_score or coalesce(fixture.away_score,0)<>live.away_score
  );
  select count(*) into v_processed from public.gameweek_lineup_snapshots
  where league_id=v_run.league_id and gameweek=v_run.gameweek and status='PROCESSED';
  return jsonb_build_object('success',true,'run_id',v_run.id,'phase',v_run.phase,'checks',jsonb_build_array(
    jsonb_build_object('key','fixtures','label','Every manager has exactly one fixture','passed',v_bad_appearances=0 and v_fixtures=ceil(v_managers/2.0),'detail',v_fixtures||' fixtures for '||v_managers||' managers'),
    jsonb_build_object('key','snapshots','label','Deadline lineups captured','passed',case when v_run.phase='PRE_DEADLINE' then v_snapshots=0 else v_snapshots=v_managers end,'detail',v_snapshots||' of '||v_managers||' snapshots'),
    jsonb_build_object('key','formations','label','Effective lineups remain legal','passed',v_invalid_lineups=0,'detail',v_invalid_lineups||' invalid lineups'),
    jsonb_build_object('key','scores','label','Fixture and player totals reconcile','passed',v_score_mismatches=0,'detail',v_score_mismatches||' mismatches'),
    jsonb_build_object('key','autosubs','label','Autosubs processed when requested','passed',case when v_run.phase in ('AUTOSUBS','WAIVERS_OPEN') then v_processed=v_managers else true end,'detail',v_processed||' processed lineups'),
    jsonb_build_object('key','sync','label','Official live sync is paused','passed',true,'detail','Paused until reset or expiry')
  ));
end;
$$;

create or replace function public.reset_gameweek_simulation(p_run_id uuid, p_reason text default 'COMMISSIONER_RESET')
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_run public.gameweek_simulation_runs%rowtype;
begin
  select * into v_run from public.gameweek_simulation_runs where id=p_run_id and status='ACTIVE';
  if not found then return jsonb_build_object('success',false,'error','ACTIVE_RUN_NOT_FOUND'); end if;
  if v_run.commissioner_id<>auth.uid() then return jsonb_build_object('success',false,'error','COMMISSIONER_REQUIRED'); end if;
  return public.restore_gameweek_simulation_internal(p_run_id, coalesce(nullif(trim(p_reason),''),'COMMISSIONER_RESET'));
end;
$$;

-- Suppress external FPL ingestion during a rehearsal. The next ordinary cron
-- tick restores an expired run before normal lifecycle work resumes.
create or replace function public.trigger_live_stats_sync()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare v_current_gw integer; v_cron_secret text; v_request_id bigint;
begin
  if exists (select 1 from public.gameweek_simulation_runs where status='ACTIVE' and expires_at>now()) then return; end if;
  select gameweek_number into v_current_gw from public.gameweeks
  where not coalesce(is_finished,false) and fpl_deadline_time<=now()
  order by coalesce(is_current,false) desc, gameweek_number desc limit 1;
  if v_current_gw is null then return; end if;
  select decrypted_secret into v_cron_secret from vault.decrypted_secrets where name='live_stats_cron_secret' limit 1;
  if v_cron_secret is null then raise warning 'live_stats_cron_secret is not configured; live stats sync skipped'; return; end if;
  select net.http_get(
    url := 'https://fnysbiwhwcqqqdwvhkau.supabase.co/functions/v1/sync-live-stats?gameweek='||v_current_gw,
    headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',v_cron_secret)
  ) into v_request_id;
end;
$$;

create or replace function public.run_gameweek_lineup_lifecycle()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_expired jsonb; v_schedule jsonb; v_snapshots jsonb; v_autosubs jsonb;
begin
  v_expired := public.expire_gameweek_simulations();
  if exists (select 1 from public.gameweek_simulation_runs where status='ACTIVE' and expires_at>now()) then
    return jsonb_build_object('success',true,'simulation_paused',true,'expiry',v_expired);
  end if;
  v_schedule:=public.refresh_league_gameweek_schedule();
  v_snapshots:=public.capture_due_gameweek_lineups(null);
  v_autosubs:=public.process_due_gameweek_autosubs(null);
  perform public.trigger_live_stats_sync();
  return jsonb_build_object('success',true,'schedule',v_schedule,'snapshots',v_snapshots,'autosubs',v_autosubs,'live_sync_checked',true,'expiry',v_expired);
end;
$$;

revoke all on function public.restore_gameweek_simulation_internal(uuid,text) from public,anon,authenticated;
revoke all on function public.expire_gameweek_simulations() from public,anon,authenticated;
revoke all on function public.get_gameweek_simulation_status(uuid) from public,anon;
revoke all on function public.start_gameweek_simulation(uuid,integer,integer) from public,anon;
revoke all on function public.advance_gameweek_simulation(uuid,text) from public,anon;
revoke all on function public.set_gameweek_simulation_player_stats(uuid,integer,text,jsonb) from public,anon;
revoke all on function public.get_gameweek_simulation_players(uuid) from public,anon;
revoke all on function public.get_gameweek_simulation_integrity(uuid) from public,anon;
revoke all on function public.reset_gameweek_simulation(uuid,text) from public,anon;
grant execute on function public.get_gameweek_simulation_status(uuid) to authenticated,service_role;
grant execute on function public.start_gameweek_simulation(uuid,integer,integer) to authenticated,service_role;
grant execute on function public.advance_gameweek_simulation(uuid,text) to authenticated,service_role;
grant execute on function public.set_gameweek_simulation_player_stats(uuid,integer,text,jsonb) to authenticated,service_role;
grant execute on function public.get_gameweek_simulation_players(uuid) to authenticated,service_role;
grant execute on function public.get_gameweek_simulation_integrity(uuid) to authenticated,service_role;
grant execute on function public.reset_gameweek_simulation(uuid,text) to authenticated,service_role;
grant execute on function public.restore_gameweek_simulation_internal(uuid,text) to service_role;
grant execute on function public.expire_gameweek_simulations() to service_role;

comment on table public.gameweek_simulation_runs is
  'Short-lived, commissioner-only Gameweek rehearsals with complete league and shared Gameweek rollback snapshots.';
