-- Draft reliability bundle:
-- 1. Persist how and why every pick was made.
-- 2. Mark a manager away after two consecutive timer autopicks.
-- 3. Autopick future away-manager turns on the next server ticker pass.
-- 4. Provide a league-visible audit trail and a safe "I'm back" RPC.

alter table public.draft_picks
  add column if not exists pick_source text not null default 'MANUAL',
  add column if not exists pick_reason text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'draft_picks_pick_source_check'
      and conrelid = 'public.draft_picks'::regclass
  ) then
    alter table public.draft_picks
      add constraint draft_picks_pick_source_check
      check (pick_source in ('MANUAL', 'AUTO_WATCHLIST', 'AUTO_PLAYER_POOL', 'COMMISSIONER'));
  end if;
end;
$$;

create table if not exists public.draft_manager_autopick_state (
  league_id uuid not null references public.leagues(id) on delete cascade,
  user_id uuid not null,
  consecutive_autopicks integer not null default 0 check (consecutive_autopicks >= 0),
  is_away boolean not null default false,
  last_autopick_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (league_id, user_id),
  foreign key (league_id, user_id)
    references public.league_members(league_id, user_id)
    on delete cascade
);

create table if not exists public.draft_pick_audit (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  pick_id bigint references public.draft_picks(id) on delete set null,
  event_type text not null default 'PICK_CREATED',
  user_id uuid,
  player_id integer,
  round_number integer,
  overall_pick_number integer,
  pick_source text not null,
  pick_reason text,
  actor_user_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists draft_pick_audit_created_pick_uidx
  on public.draft_pick_audit(pick_id)
  where event_type = 'PICK_CREATED';

create index if not exists draft_pick_audit_league_pick_idx
  on public.draft_pick_audit(league_id, overall_pick_number, created_at);

alter table public.draft_manager_autopick_state enable row level security;
alter table public.draft_pick_audit enable row level security;

drop policy if exists "League members can view draft autopick state"
  on public.draft_manager_autopick_state;
create policy "League members can view draft autopick state"
  on public.draft_manager_autopick_state
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.league_members lm
      where lm.league_id = draft_manager_autopick_state.league_id
        and lm.user_id = auth.uid()
    )
  );

drop policy if exists "League members can view draft pick audit"
  on public.draft_pick_audit;
create policy "League members can view draft pick audit"
  on public.draft_pick_audit
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.league_members lm
      where lm.league_id = draft_pick_audit.league_id
        and lm.user_id = auth.uid()
    )
  );

create or replace function public.execute_draft_pick(
  p_league_id uuid,
  p_user_id uuid,
  p_player_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session record;
  v_next_picker_id uuid;
  v_next_pick_index integer;
  v_total_members integer;
  v_next_round integer;
  v_snake_slot integer;
  v_turn_duration integer := 60;
  v_max_picks integer;
  v_pick_id bigint;
  v_next_manager_away boolean := false;
begin
  select *
  into v_session
  from public.draft_sessions
  where league_id = p_league_id
  for update;

  if v_session is null
     or v_session.draft_status not in ('LIVE', 'DRAFTING') then
    return jsonb_build_object('success', false, 'error', 'DRAFT_NOT_ACTIVE');
  end if;

  if v_session.current_picker_id is distinct from p_user_id then
    return jsonb_build_object('success', false, 'error', 'NOT_YOUR_TURN');
  end if;

  if exists (
    select 1 from public.draft_picks
    where league_id = p_league_id and player_id = p_player_id
  ) then
    return jsonb_build_object('success', false, 'error', 'PLAYER_ALREADY_TAKEN');
  end if;

  select count(*) into v_total_members
  from public.league_members
  where league_id = p_league_id;

  if v_total_members = 0 then
    return jsonb_build_object('success', false, 'error', 'NO_LEAGUE_MEMBERS');
  end if;

  select coalesce(draft_clock_duration, 60)
  into v_turn_duration
  from public.league_settings
  where league_id = p_league_id;

  insert into public.draft_picks (
    league_id, user_id, player_id, round_number, overall_pick_number,
    pick_source, pick_reason
  ) values (
    p_league_id, p_user_id, p_player_id,
    v_session.current_round, v_session.current_pick_index,
    'MANUAL', null
  )
  returning id into v_pick_id;

  insert into public.rosters (league_id, user_id, player_id, is_starting)
  values (p_league_id, p_user_id, p_player_id, true);

  insert into public.draft_pick_audit (
    league_id, pick_id, event_type, user_id, player_id,
    round_number, overall_pick_number, pick_source, pick_reason,
    actor_user_id, metadata
  ) values (
    p_league_id, v_pick_id, 'PICK_CREATED', p_user_id, p_player_id,
    v_session.current_round, v_session.current_pick_index, 'MANUAL', null,
    p_user_id, jsonb_build_object('turn_deadline', v_session.pick_deadline)
  );

  -- A successful manual pick proves the manager has returned.
  insert into public.draft_manager_autopick_state (
    league_id, user_id, consecutive_autopicks, is_away, updated_at
  ) values (p_league_id, p_user_id, 0, false, now())
  on conflict (league_id, user_id) do update
  set consecutive_autopicks = 0,
      is_away = false,
      updated_at = now();

  v_max_picks := v_total_members * 15;
  v_next_pick_index := v_session.current_pick_index + 1;

  if v_next_pick_index > v_max_picks then
    update public.draft_sessions
    set draft_status = 'COMPLETED', pick_deadline = null
    where league_id = p_league_id;

    update public.leagues
    set draft_status = 'COMPLETED', status = 'IN_SEASON'
    where id = p_league_id;

    return jsonb_build_object(
      'success', true,
      'completed', true,
      'pick_id', v_pick_id
    );
  end if;

  v_next_round := ceil(v_next_pick_index::numeric / v_total_members)::integer;
  v_snake_slot := ((v_next_pick_index - 1) % v_total_members) + 1;

  if v_next_round % 2 = 0 then
    v_snake_slot := v_total_members - v_snake_slot + 1;
  end if;

  select user_id into v_next_picker_id
  from public.league_members
  where league_id = p_league_id and draft_order = v_snake_slot
  limit 1;

  if v_next_picker_id is null then
    raise exception 'No manager found for draft slot % in league %', v_snake_slot, p_league_id;
  end if;

  select coalesce(s.is_away, false)
  into v_next_manager_away
  from public.draft_manager_autopick_state s
  where s.league_id = p_league_id and s.user_id = v_next_picker_id;

  v_next_manager_away := coalesce(v_next_manager_away, false);

  update public.draft_sessions
  set current_pick_index = v_next_pick_index,
      current_round = v_next_round,
      current_picker_id = v_next_picker_id,
      pick_deadline = case
        when v_next_manager_away then now()
        else now() + (v_turn_duration || ' seconds')::interval
      end
  where league_id = p_league_id;

  return jsonb_build_object(
    'success', true,
    'completed', false,
    'pick_id', v_pick_id,
    'next_pick_index', v_next_pick_index,
    'next_round', v_next_round,
    'next_picker_id', v_next_picker_id,
    'next_draft_slot', v_snake_slot,
    'next_manager_away', v_next_manager_away
  );
end;
$$;

create or replace function public.execute_draft_autopick(
  p_league_id uuid,
  p_user_id uuid,
  p_pick_number integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session record;
  v_candidate record;
  v_pick_result jsonb;
  v_last_error text;
  v_previous_count integer := 0;
  v_was_away boolean := false;
  v_new_count integer;
  v_reason text;
  v_source text;
  v_pick_id bigint;
begin
  select * into v_session
  from public.draft_sessions
  where league_id = p_league_id
  for update;

  if v_session is null or v_session.draft_status not in ('LIVE', 'DRAFTING') then
    return jsonb_build_object('success', false, 'error', 'DRAFT_NOT_ACTIVE');
  end if;

  if v_session.current_picker_id is distinct from p_user_id then
    return jsonb_build_object('success', false, 'error', 'NOT_CURRENT_PICKER');
  end if;

  if v_session.current_pick_index is distinct from p_pick_number then
    return jsonb_build_object(
      'success', false,
      'error', 'STALE_PICK_NUMBER',
      'expected_pick_number', v_session.current_pick_index,
      'received_pick_number', p_pick_number
    );
  end if;

  select coalesce(consecutive_autopicks, 0), coalesce(is_away, false)
  into v_previous_count, v_was_away
  from public.draft_manager_autopick_state
  where league_id = p_league_id and user_id = p_user_id;

  v_previous_count := coalesce(v_previous_count, 0);
  v_was_away := coalesce(v_was_away, false);
  v_reason := case when v_was_away then 'MANAGER_AWAY' else 'TIMER_EXPIRED' end;

  for v_candidate in
    select w.player_id
    from public.watchlists w
    join public.players p on p.id = w.player_id
    where w.league_id = p_league_id
      and w.user_id = p_user_id
      and not exists (
        select 1 from public.draft_picks dp
        where dp.league_id = p_league_id and dp.player_id = w.player_id
      )
    order by w.priority_order asc, coalesce(p.draft_rank, 999999) asc, p.total_points desc
  loop
    begin
      v_pick_result := public.execute_draft_pick(p_league_id, p_user_id, v_candidate.player_id);
      if coalesce((v_pick_result ->> 'success')::boolean, false) then
        v_source := 'AUTO_WATCHLIST';
        exit;
      end if;
      v_last_error := v_pick_result ->> 'error';
    exception when others then
      v_last_error := sqlerrm;
    end;
  end loop;

  if v_source is null then
    for v_candidate in
      select p.id as player_id
      from public.players p
      where not exists (
        select 1 from public.draft_picks dp
        where dp.league_id = p_league_id and dp.player_id = p.id
      )
      order by coalesce(p.draft_rank, 999999) asc, p.total_points desc, p.id asc
    loop
      begin
        v_pick_result := public.execute_draft_pick(p_league_id, p_user_id, v_candidate.player_id);
        if coalesce((v_pick_result ->> 'success')::boolean, false) then
          v_source := 'AUTO_PLAYER_POOL';
          exit;
        end if;
        v_last_error := v_pick_result ->> 'error';
      exception when others then
        v_last_error := sqlerrm;
      end;
    end loop;
  end if;

  if v_source is null then
    return jsonb_build_object(
      'success', false,
      'error', 'NO_ELIGIBLE_PLAYERS',
      'last_candidate_error', v_last_error
    );
  end if;

  v_pick_id := (v_pick_result ->> 'pick_id')::bigint;
  v_new_count := v_previous_count + 1;

  update public.draft_picks
  set pick_source = v_source, pick_reason = v_reason
  where id = v_pick_id;

  update public.draft_pick_audit
  set pick_source = v_source,
      pick_reason = v_reason,
      actor_user_id = null,
      metadata = metadata || jsonb_build_object(
        'autopick_number', v_new_count,
        'away_threshold', 2
      )
  where pick_id = v_pick_id and event_type = 'PICK_CREATED';

  insert into public.draft_manager_autopick_state (
    league_id, user_id, consecutive_autopicks, is_away,
    last_autopick_at, updated_at
  ) values (
    p_league_id, p_user_id, v_new_count,
    v_was_away or v_new_count >= 2, now(), now()
  )
  on conflict (league_id, user_id) do update
  set consecutive_autopicks = excluded.consecutive_autopicks,
      is_away = excluded.is_away,
      last_autopick_at = excluded.last_autopick_at,
      updated_at = excluded.updated_at;

  return v_pick_result || jsonb_build_object(
    'autopick', true,
    'autopick_source', case
      when v_source = 'AUTO_WATCHLIST' then 'WATCHLIST'
      else 'PLAYER_POOL'
    end,
    'autopick_reason', v_reason,
    'autopicked_player_id', v_candidate.player_id,
    'consecutive_autopicks', v_new_count,
    'manager_marked_away', v_was_away or v_new_count >= 2
  );
end;
$$;

create or replace function public.process_expired_draft_sessions()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session record;
  v_result jsonb;
  v_results jsonb := '[]'::jsonb;
  v_processed integer := 0;
begin
  for v_session in
    select ds.league_id, ds.current_picker_id, ds.current_pick_index
    from public.draft_sessions ds
    left join public.draft_manager_autopick_state aps
      on aps.league_id = ds.league_id
     and aps.user_id = ds.current_picker_id
    where ds.draft_status in ('LIVE', 'DRAFTING')
      and ds.current_picker_id is not null
      and (
        (ds.pick_deadline is not null and ds.pick_deadline <= pg_catalog.now())
        or coalesce(aps.is_away, false)
      )
    order by ds.pick_deadline asc nulls first
    for update of ds skip locked
  loop
    begin
      v_result := public.execute_draft_autopick(
        v_session.league_id,
        v_session.current_picker_id,
        v_session.current_pick_index
      );
    exception when others then
      v_result := jsonb_build_object(
        'success', false,
        'error', 'AUTOPICK_EXCEPTION',
        'message', sqlerrm
      );
    end;

    if coalesce((v_result ->> 'success')::boolean, false) then
      v_processed := v_processed + 1;
    end if;

    v_results := v_results || jsonb_build_array(jsonb_build_object(
      'league_id', v_session.league_id,
      'pick_number', v_session.current_pick_index,
      'result', v_result
    ));
  end loop;

  return jsonb_build_object(
    'success', true,
    'processed', v_processed,
    'sessions', v_results,
    'checked_at', pg_catalog.now()
  );
end;
$$;

create or replace function public.mark_draft_manager_present(p_league_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_turn_duration integer := 60;
begin
  if v_user_id is null then
    return jsonb_build_object('success', false, 'error', 'AUTH_REQUIRED');
  end if;

  if not exists (
    select 1 from public.league_members
    where league_id = p_league_id and user_id = v_user_id
  ) then
    return jsonb_build_object('success', false, 'error', 'NOT_LEAGUE_MEMBER');
  end if;

  insert into public.draft_manager_autopick_state (
    league_id, user_id, consecutive_autopicks, is_away, updated_at
  ) values (p_league_id, v_user_id, 0, false, now())
  on conflict (league_id, user_id) do update
  set consecutive_autopicks = 0,
      is_away = false,
      updated_at = now();

  select coalesce(draft_clock_duration, 60)
  into v_turn_duration
  from public.league_settings
  where league_id = p_league_id;

  -- If the manager returns during their instant-away turn, restore a full
  -- clock before the ticker can claim it.
  update public.draft_sessions
  set pick_deadline = now() + (coalesce(v_turn_duration, 60) || ' seconds')::interval,
      updated_at = now()
  where league_id = p_league_id
    and current_picker_id = v_user_id
    and draft_status in ('LIVE', 'DRAFTING');

  return jsonb_build_object('success', true, 'is_away', false);
end;
$$;

revoke all on function public.execute_draft_autopick(uuid, uuid, integer)
  from public, anon, authenticated;
grant execute on function public.execute_draft_autopick(uuid, uuid, integer)
  to service_role;

revoke all on function public.process_expired_draft_sessions()
  from public, anon, authenticated;
grant execute on function public.process_expired_draft_sessions()
  to service_role;

revoke all on function public.mark_draft_manager_present(uuid)
  from public, anon;
grant execute on function public.mark_draft_manager_present(uuid)
  to authenticated;

grant select on public.draft_manager_autopick_state to authenticated;
grant select on public.draft_pick_audit to authenticated;

comment on table public.draft_manager_autopick_state is
  'Tracks consecutive missed draft turns; two timer autopicks place a manager in away mode.';
comment on table public.draft_pick_audit is
  'Immutable-facing event history for draft picks and future commissioner corrections.';
