-- Android-first push delivery foundation. Push delivery is deliberately separate
-- from the underlying notification insert, so network failures cannot block league actions.

create table if not exists public.push_device_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  expo_push_token text not null unique,
  platform text not null check (platform in ('ANDROID', 'IOS')),
  device_name text,
  enabled boolean not null default true,
  last_registered_at timestamptz not null default now(),
  last_delivery_at timestamptz,
  last_error text,
  failure_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint push_device_tokens_format check (
    expo_push_token ~ '^Expo(nent)?PushToken\[[A-Za-z0-9_-]+\]$'
  )
);

create index if not exists push_device_tokens_user_idx
  on public.push_device_tokens (user_id, enabled, last_registered_at desc);

create table if not exists public.push_delivery_attempts (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.user_notifications(id) on delete cascade,
  token_id uuid not null references public.push_device_tokens(id) on delete cascade,
  status text not null check (status in ('SENDING', 'TICKET_ACCEPTED', 'DELIVERED', 'FAILED', 'SKIPPED')),
  expo_ticket_id text,
  error_code text,
  error_message text,
  receipt_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (notification_id, token_id)
);

create index if not exists push_delivery_receipts_idx
  on public.push_delivery_attempts (status, receipt_checked_at, created_at)
  where expo_ticket_id is not null;

alter table public.push_device_tokens enable row level security;
alter table public.push_delivery_attempts enable row level security;

drop policy if exists "Managers can view their push devices" on public.push_device_tokens;
create policy "Managers can view their push devices"
  on public.push_device_tokens for select to authenticated
  using (user_id = auth.uid());

revoke all on table public.push_device_tokens from public, anon, authenticated;
grant select on table public.push_device_tokens to authenticated;
grant all on table public.push_device_tokens to service_role;
revoke all on table public.push_delivery_attempts from public, anon, authenticated;
grant all on table public.push_delivery_attempts to service_role;

alter table public.notification_preferences
  add column if not exists push_enabled boolean not null default false,
  add column if not exists draft_enabled boolean not null default true;

create or replace function public.register_push_device(
  p_expo_push_token text,
  p_platform text,
  p_device_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_token text := pg_catalog.btrim(coalesce(p_expo_push_token, ''));
  v_platform text := pg_catalog.upper(pg_catalog.btrim(coalesce(p_platform, '')));
  v_token_id uuid;
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  if v_platform not in ('ANDROID', 'IOS') then raise exception 'INVALID_PLATFORM'; end if;
  if v_token !~ '^Expo(nent)?PushToken\[[A-Za-z0-9_-]+\]$' then raise exception 'INVALID_EXPO_PUSH_TOKEN'; end if;

  insert into public.push_device_tokens (
    user_id, expo_push_token, platform, device_name, enabled,
    last_registered_at, last_error, failure_count, updated_at
  ) values (
    v_user_id, v_token, v_platform, nullif(pg_catalog.btrim(coalesce(p_device_name, '')), ''), true,
    pg_catalog.now(), null, 0, pg_catalog.now()
  )
  on conflict (expo_push_token) do update set
    user_id = excluded.user_id,
    platform = excluded.platform,
    device_name = excluded.device_name,
    enabled = true,
    last_registered_at = pg_catalog.now(),
    last_error = null,
    failure_count = 0,
    updated_at = pg_catalog.now()
  returning id into v_token_id;

  insert into public.notification_preferences (user_id, push_enabled, updated_at)
  values (v_user_id, true, pg_catalog.now())
  on conflict (user_id) do update set push_enabled = true, updated_at = pg_catalog.now();

  return v_token_id;
end;
$$;

create or replace function public.disable_my_push_devices()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare v_count integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  update public.push_device_tokens
  set enabled = false, updated_at = pg_catalog.now()
  where user_id = auth.uid() and enabled;
  get diagnostics v_count = row_count;

  insert into public.notification_preferences (user_id, push_enabled, updated_at)
  values (auth.uid(), false, pg_catalog.now())
  on conflict (user_id) do update set push_enabled = false, updated_at = pg_catalog.now();
  return v_count;
end;
$$;

revoke all on function public.register_push_device(text, text, text) from public, anon;
grant execute on function public.register_push_device(text, text, text) to authenticated;
revoke all on function public.disable_my_push_devices() from public, anon;
grant execute on function public.disable_my_push_devices() to authenticated;

create or replace function public.create_test_push_notification()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare v_notification_id bigint;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  insert into public.user_notifications (
    user_id, league_id, category, title, body, route, dedupe_key
  ) values (
    auth.uid(), null, 'SYSTEM', 'Push notifications are working',
    'This is a private test sent only to your registered device.',
    '/notifications', null
  ) returning id into v_notification_id;
  return v_notification_id;
end;
$$;

revoke all on function public.create_test_push_notification() from public, anon;
grant execute on function public.create_test_push_notification() to authenticated;

-- Queue draft waiting-room and start alerts through the existing in-app inbox.
-- The Edge Function webhook decides whether each inbox record also becomes push.
create or replace function public.enqueue_due_draft_notifications()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_waiting integer := 0; v_live integer := 0;
begin
  insert into public.user_notifications (
    user_id, league_id, category, title, body, route, dedupe_key
  )
  select member.user_id, settings.league_id, 'SYSTEM',
    'Draft waiting room is open',
    'Your draft starts in around 10 minutes. Ready up and review your watchlist.',
    '/draft-room?leagueId=' || settings.league_id,
    'draft-waiting:' || settings.league_id || ':' || extract(epoch from settings.draft_start_time)::bigint
  from public.league_settings settings
  join public.leagues league on league.id = settings.league_id
  join public.league_members member on member.league_id = settings.league_id
  left join public.notification_preferences preference on preference.user_id = member.user_id
  where settings.draft_start_time > pg_catalog.now()
    and settings.draft_start_time <= pg_catalog.now() + interval '10 minutes'
    and upper(coalesce(league.draft_status, league.status, 'PRE_DRAFT')) in ('PRE_DRAFT', 'WAITING_ROOM', 'NOT_STARTED', 'WAITING')
    and coalesce(preference.draft_enabled, true)
  on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  get diagnostics v_waiting = row_count;

  insert into public.user_notifications (
    user_id, league_id, category, title, body, route, dedupe_key
  )
  select member.user_id, settings.league_id, 'SYSTEM',
    'Your league draft is starting',
    'Enter the draft room now. The first manager will be on the clock.',
    '/draft-room?leagueId=' || settings.league_id,
    'draft-start:' || settings.league_id || ':' || extract(epoch from settings.draft_start_time)::bigint
  from public.league_settings settings
  join public.leagues league on league.id = settings.league_id
  join public.league_members member on member.league_id = settings.league_id
  left join public.notification_preferences preference on preference.user_id = member.user_id
  where settings.draft_start_time <= pg_catalog.now()
    and settings.draft_start_time > pg_catalog.now() - interval '30 minutes'
    and upper(coalesce(league.draft_status, league.status, 'PRE_DRAFT')) not in ('COMPLETED', 'FINISHED')
    and coalesce(preference.draft_enabled, true)
  on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  get diagnostics v_live = row_count;

  return jsonb_build_object('success', true, 'waiting_room_notifications', v_waiting, 'draft_start_notifications', v_live);
end;
$$;

revoke all on function public.enqueue_due_draft_notifications() from public, anon, authenticated;
grant execute on function public.enqueue_due_draft_notifications() to service_role;

do $$
declare v_job_id bigint;
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    for v_job_id in select jobid from cron.job where jobname = 'draft-push-notification-queue' loop
      perform cron.unschedule(v_job_id);
    end loop;
    perform cron.schedule(
      'draft-push-notification-queue',
      '* * * * *',
      'select public.enqueue_due_draft_notifications();'
    );
  end if;
end;
$$;
