-- League cups V1: secure single-knockout creation, live scoring and
-- repeat-safe progression after official Gameweek finalization.

create table if not exists public.cups (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  name text not null check (pg_catalog.char_length(pg_catalog.btrim(name)) between 1 and 60),
  format text not null default 'SINGLE_KNOCKOUT'
    check (format in ('SINGLE_KNOCKOUT')),
  status text not null default 'SCHEDULED'
    check (status in ('SCHEDULED', 'LIVE', 'COMPLETED', 'CANCELLED')),
  start_gameweek integer not null check (start_gameweek between 1 and 38),
  round_count integer not null check (round_count between 1 and 6),
  participant_count integer not null check (participant_count between 2 and 64),
  seeding_method text not null default 'RANDOM' check (seeding_method in ('RANDOM')),
  tie_breakers text[] not null default array[
    'HIGHEST_STARTER', 'MOST_GOALS', 'MOST_ASSISTS', 'HIGHER_SEED'
  ]::text[],
  champion_user_id uuid references auth.users(id) on delete set null,
  runner_up_user_id uuid references auth.users(id) on delete set null,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  unique (league_id, name)
);

create table if not exists public.cup_entries (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  cup_id uuid not null references public.cups(id) on delete cascade,
  league_id uuid not null references public.leagues(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  seed integer not null check (seed > 0),
  status text not null default 'ACTIVE'
    check (status in ('ACTIVE', 'ELIMINATED', 'CHAMPION')),
  eliminated_round integer,
  created_at timestamptz not null default pg_catalog.now(),
  unique (cup_id, user_id),
  unique (cup_id, seed)
);

create table if not exists public.cup_rounds (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  cup_id uuid not null references public.cups(id) on delete cascade,
  league_id uuid not null references public.leagues(id) on delete cascade,
  round_number integer not null check (round_number > 0),
  name text not null,
  gameweek integer not null check (gameweek between 1 and 38),
  status text not null default 'SCHEDULED'
    check (status in ('SCHEDULED', 'LIVE', 'COMPLETED')),
  created_at timestamptz not null default pg_catalog.now(),
  unique (cup_id, round_number),
  unique (cup_id, gameweek)
);

create table if not exists public.cup_fixtures (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  cup_id uuid not null references public.cups(id) on delete cascade,
  league_id uuid not null references public.leagues(id) on delete cascade,
  round_id uuid not null references public.cup_rounds(id) on delete cascade,
  round_number integer not null check (round_number > 0),
  match_number integer not null check (match_number > 0),
  gameweek integer not null check (gameweek between 1 and 38),
  home_user_id uuid references auth.users(id) on delete set null,
  away_user_id uuid references auth.users(id) on delete set null,
  home_score integer,
  away_score integer,
  winner_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'SCHEDULED'
    check (status in ('SCHEDULED', 'LIVE', 'COMPLETED', 'BYE')),
  resolution text,
  finished_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  unique (round_id, match_number),
  check (home_user_id is null or away_user_id is null or home_user_id <> away_user_id)
);

create table if not exists public.cup_audit_log (
  id bigint generated by default as identity primary key,
  cup_id uuid not null references public.cups(id) on delete cascade,
  league_id uuid not null references public.leagues(id) on delete cascade,
  action text not null,
  actor_id uuid references auth.users(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default pg_catalog.now()
);

create index if not exists cups_league_status_idx
  on public.cups(league_id, status, start_gameweek);
create unique index if not exists cups_league_name_ci_idx
  on public.cups(league_id, pg_catalog.lower(name));
create index if not exists cup_entries_league_user_idx
  on public.cup_entries(league_id, user_id);
create index if not exists cup_rounds_schedule_idx
  on public.cup_rounds(league_id, gameweek, status);
create index if not exists cup_fixtures_schedule_idx
  on public.cup_fixtures(league_id, gameweek, status);

alter table public.cups enable row level security;
alter table public.cup_entries enable row level security;
alter table public.cup_rounds enable row level security;
alter table public.cup_fixtures enable row level security;
alter table public.cup_audit_log enable row level security;

drop policy if exists "League members can view cups" on public.cups;
create policy "League members can view cups"
on public.cups for select to authenticated
using (exists (
  select 1 from public.league_members member
  where member.league_id = cups.league_id and member.user_id = auth.uid()
));

drop policy if exists "League members can view cup entries" on public.cup_entries;
create policy "League members can view cup entries"
on public.cup_entries for select to authenticated
using (exists (
  select 1 from public.league_members member
  where member.league_id = cup_entries.league_id and member.user_id = auth.uid()
));

drop policy if exists "League members can view cup rounds" on public.cup_rounds;
create policy "League members can view cup rounds"
on public.cup_rounds for select to authenticated
using (exists (
  select 1 from public.league_members member
  where member.league_id = cup_rounds.league_id and member.user_id = auth.uid()
));

drop policy if exists "League members can view cup fixtures" on public.cup_fixtures;
create policy "League members can view cup fixtures"
on public.cup_fixtures for select to authenticated
using (exists (
  select 1 from public.league_members member
  where member.league_id = cup_fixtures.league_id and member.user_id = auth.uid()
));

drop policy if exists "League members can view cup audit" on public.cup_audit_log;
create policy "League members can view cup audit"
on public.cup_audit_log for select to authenticated
using (exists (
  select 1 from public.league_members member
  where member.league_id = cup_audit_log.league_id and member.user_id = auth.uid()
));

revoke insert, update, delete on public.cups from anon, authenticated;
revoke insert, update, delete on public.cup_entries from anon, authenticated;
revoke insert, update, delete on public.cup_rounds from anon, authenticated;
revoke insert, update, delete on public.cup_fixtures from anon, authenticated;
revoke insert, update, delete on public.cup_audit_log from anon, authenticated;
grant select on public.cups, public.cup_entries, public.cup_rounds,
  public.cup_fixtures, public.cup_audit_log to authenticated;

create or replace function public.get_cup_manager_gameweek_score(
  p_league_id uuid,
  p_user_id uuid,
  p_gameweek integer
)
returns table(
  total_score integer,
  fpl_points integer,
  defcon_points integer,
  highest_starter integer,
  goals integer,
  assists integer
)
language sql
stable
security definer
set search_path = ''
as $$
  with selected_players as (
    select selected.player_id
    from public.gameweek_lineup_snapshots snapshot
    cross join lateral pg_catalog.unnest(snapshot.effective_starting_player_ids) selected(player_id)
    where snapshot.league_id = p_league_id
      and snapshot.user_id = p_user_id
      and snapshot.gameweek = p_gameweek

    union all

    select roster.player_id
    from public.rosters roster
    where roster.league_id = p_league_id
      and roster.user_id = p_user_id
      and roster.is_starting
      and not exists (
        select 1 from public.gameweek_lineup_snapshots snapshot
        where snapshot.league_id = p_league_id
          and snapshot.user_id = p_user_id
          and snapshot.gameweek = p_gameweek
      )
  ), player_scores as (
    select
      coalesce(stats.total_points, 0)::integer as fpl_points,
      public.calculate_player_defcon_points(
        p_league_id,
        player.element_type::text,
        coalesce(stats.defensive_contribution, 0)::integer
      )::integer as defcon_points,
      coalesce(stats.goals_scored, 0)::integer as goals,
      coalesce(stats.assists, 0)::integer as assists
    from selected_players selected
    join public.players player on player.id = selected.player_id
    left join public.player_gameweek_stats stats
      on stats.player_id = selected.player_id and stats.gameweek = p_gameweek
  )
  select
    coalesce(pg_catalog.sum(score.fpl_points + score.defcon_points), 0)::integer,
    coalesce(pg_catalog.sum(score.fpl_points), 0)::integer,
    coalesce(pg_catalog.sum(score.defcon_points), 0)::integer,
    coalesce(pg_catalog.max(score.fpl_points + score.defcon_points), 0)::integer,
    coalesce(pg_catalog.sum(score.goals), 0)::integer,
    coalesce(pg_catalog.sum(score.assists), 0)::integer
  from player_scores score;
$$;

revoke all on function public.get_cup_manager_gameweek_score(uuid, uuid, integer)
  from public, anon, authenticated;
grant execute on function public.get_cup_manager_gameweek_score(uuid, uuid, integer)
  to service_role;

create or replace function public.create_single_knockout_cup(
  p_league_id uuid,
  p_name text,
  p_start_gameweek integer,
  p_participant_ids uuid[] default null,
  p_tie_breakers text[] default array[
    'HIGHEST_STARTER', 'MOST_GOALS', 'MOST_ASSISTS', 'HIGHER_SEED'
  ]::text[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_name text := nullif(pg_catalog.btrim(coalesce(p_name, '')), '');
  v_cup_id uuid := pg_catalog.gen_random_uuid();
  v_participants uuid[];
  v_participant_count integer;
  v_bracket_size integer := 1;
  v_round_count integer := 0;
  v_round_number integer;
  v_round_size integer;
  v_round_name text;
  v_round_id uuid;
  v_opening_matches integer;
  v_contested_matches integer;
  v_match integer;
  v_home_seed integer;
  v_away_seed integer;
  v_home_user uuid;
  v_away_user uuid;
  v_allowed_breakers constant text[] := array[
    'HIGHEST_STARTER', 'MOST_GOALS', 'MOST_ASSISTS', 'HIGHER_SEED'
  ]::text[];
begin
  if v_user_id is null then
    return jsonb_build_object('success', false, 'error', 'AUTH_REQUIRED');
  end if;

  if not exists (
    select 1 from public.leagues league
    where league.id = p_league_id and league.commissioner_id = v_user_id
  ) then
    return jsonb_build_object('success', false, 'error', 'COMMISSIONER_REQUIRED');
  end if;

  if v_name is null or pg_catalog.char_length(v_name) > 60 then
    return jsonb_build_object('success', false, 'error', 'INVALID_CUP_NAME');
  end if;

  if p_start_gameweek is null or p_start_gameweek not between 1 and 38 then
    return jsonb_build_object('success', false, 'error', 'INVALID_START_GAMEWEEK');
  end if;

  if p_tie_breakers is null
     or pg_catalog.cardinality(p_tie_breakers) <> pg_catalog.cardinality(v_allowed_breakers)
     or p_tie_breakers @> v_allowed_breakers is false
     or v_allowed_breakers @> p_tie_breakers is false then
    return jsonb_build_object('success', false, 'error', 'INVALID_TIE_BREAKERS');
  end if;

  select pg_catalog.array_agg(member.user_id order by member.user_id)
  into v_participants
  from public.league_members member
  where member.league_id = p_league_id
    and (
      p_participant_ids is null
      or member.user_id = any(p_participant_ids)
    );

  v_participant_count := coalesce(pg_catalog.cardinality(v_participants), 0);
  if v_participant_count < 2 then
    return jsonb_build_object('success', false, 'error', 'INSUFFICIENT_PARTICIPANTS');
  end if;

  if p_participant_ids is not null
     and v_participant_count <> pg_catalog.cardinality(p_participant_ids) then
    return jsonb_build_object('success', false, 'error', 'INVALID_PARTICIPANT');
  end if;

  while v_bracket_size < v_participant_count loop
    v_bracket_size := v_bracket_size * 2;
    v_round_count := v_round_count + 1;
  end loop;

  if p_start_gameweek + v_round_count - 1 > 38 then
    return jsonb_build_object('success', false, 'error', 'SCHEDULE_EXCEEDS_SEASON');
  end if;

  if exists (
    select 1 from public.cups cup
    where cup.league_id = p_league_id
      and pg_catalog.lower(cup.name) = pg_catalog.lower(v_name)
  ) then
    return jsonb_build_object('success', false, 'error', 'CUP_NAME_TAKEN');
  end if;

  insert into public.cups (
    id, league_id, name, start_gameweek, round_count, participant_count,
    seeding_method, tie_breakers, created_by
  ) values (
    v_cup_id, p_league_id, v_name, p_start_gameweek, v_round_count,
    v_participant_count, 'RANDOM', p_tie_breakers, v_user_id
  );

  insert into public.cup_entries (cup_id, league_id, user_id, seed)
  select
    v_cup_id,
    p_league_id,
    participant.user_id,
    row_number() over (
      order by pg_catalog.md5(participant.user_id::text || v_cup_id::text)
    )::integer
  from pg_catalog.unnest(v_participants) participant(user_id);

  for v_round_number in 1..v_round_count loop
    v_round_size := v_bracket_size / pg_catalog.power(2, v_round_number - 1)::integer;
    v_round_name := case
      when v_round_size = 2 then 'FINAL'
      when v_round_size = 4 then 'SEMI-FINALS'
      when v_round_size = 8 then 'QUARTER-FINALS'
      else 'ROUND OF ' || v_round_size::text
    end;

    insert into public.cup_rounds (
      cup_id, league_id, round_number, name, gameweek
    ) values (
      v_cup_id, p_league_id, v_round_number, v_round_name,
      p_start_gameweek + v_round_number - 1
    );
  end loop;

  select round.id into v_round_id
  from public.cup_rounds round
  where round.cup_id = v_cup_id and round.round_number = 1;

  v_opening_matches := v_bracket_size / 2;
  v_contested_matches := v_participant_count - v_opening_matches;

  for v_match in 1..v_opening_matches loop
    if v_match <= v_contested_matches then
      v_home_seed := ((v_match - 1) * 2) + 1;
      v_away_seed := v_home_seed + 1;
    else
      v_home_seed := (v_contested_matches * 2) + (v_match - v_contested_matches);
      v_away_seed := null;
    end if;

    select entry.user_id into v_home_user
    from public.cup_entries entry
    where entry.cup_id = v_cup_id and entry.seed = v_home_seed;

    v_away_user := null;
    if v_away_seed is not null then
      select entry.user_id into v_away_user
      from public.cup_entries entry
      where entry.cup_id = v_cup_id and entry.seed = v_away_seed;
    end if;

    insert into public.cup_fixtures (
      cup_id, league_id, round_id, round_number, match_number, gameweek,
      home_user_id, away_user_id, winner_user_id, status, resolution, finished_at
    ) values (
      v_cup_id, p_league_id, v_round_id, 1, v_match, p_start_gameweek,
      v_home_user, v_away_user,
      case when v_away_user is null then v_home_user else null end,
      case when v_away_user is null then 'BYE' else 'SCHEDULED' end,
      case when v_away_user is null then 'BYE' else null end,
      case when v_away_user is null then pg_catalog.now() else null end
    );
  end loop;

  insert into public.cup_audit_log (cup_id, league_id, action, actor_id, details)
  values (
    v_cup_id, p_league_id, 'CUP_CREATED', v_user_id,
    jsonb_build_object(
      'participants', v_participant_count,
      'rounds', v_round_count,
      'start_gameweek', p_start_gameweek,
      'seeding', 'RANDOM'
    )
  );

  return jsonb_build_object(
    'success', true,
    'cup_id', v_cup_id,
    'participants', v_participant_count,
    'rounds', v_round_count,
    'final_gameweek', p_start_gameweek + v_round_count - 1
  );
exception when unique_violation then
  return jsonb_build_object('success', false, 'error', 'CUP_NAME_TAKEN');
end;
$$;

revoke all on function public.create_single_knockout_cup(uuid, text, integer, uuid[], text[])
  from public, anon;
grant execute on function public.create_single_knockout_cup(uuid, text, integer, uuid[], text[])
  to authenticated, service_role;

create or replace function public.finalize_cup_gameweek(p_gameweek integer)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_fixture record;
  v_round record;
  v_home record;
  v_away record;
  v_breaker text;
  v_winner uuid;
  v_loser uuid;
  v_resolution text;
  v_home_seed integer;
  v_away_seed integer;
  v_winners uuid[];
  v_next_round_id uuid;
  v_index integer;
  v_updated integer := 0;
  v_completed_cups integer := 0;
begin
  if not exists (
    select 1 from public.gameweeks gameweek
    where gameweek.gameweek_number = p_gameweek
      and coalesce(gameweek.is_finished, false)
  ) then
    return jsonb_build_object('success', false, 'error', 'GAMEWEEK_NOT_FINISHED');
  end if;

  for v_fixture in
    select fixture.*, cup.tie_breakers
    from public.cup_fixtures fixture
    join public.cups cup on cup.id = fixture.cup_id
    where fixture.gameweek = p_gameweek
      and fixture.status in ('SCHEDULED', 'LIVE')
      and fixture.home_user_id is not null
      and fixture.away_user_id is not null
    order by fixture.cup_id, fixture.round_number, fixture.match_number
    for update of fixture skip locked
  loop
    select * into v_home
    from public.get_cup_manager_gameweek_score(
      v_fixture.league_id, v_fixture.home_user_id, p_gameweek
    );
    select * into v_away
    from public.get_cup_manager_gameweek_score(
      v_fixture.league_id, v_fixture.away_user_id, p_gameweek
    );

    v_winner := null;
    v_resolution := 'TOTAL_SCORE';
    if v_home.total_score > v_away.total_score then
      v_winner := v_fixture.home_user_id;
    elsif v_away.total_score > v_home.total_score then
      v_winner := v_fixture.away_user_id;
    else
      foreach v_breaker in array v_fixture.tie_breakers loop
        if v_breaker = 'HIGHEST_STARTER' and v_home.highest_starter <> v_away.highest_starter then
          v_winner := case when v_home.highest_starter > v_away.highest_starter
            then v_fixture.home_user_id else v_fixture.away_user_id end;
        elsif v_breaker = 'MOST_GOALS' and v_home.goals <> v_away.goals then
          v_winner := case when v_home.goals > v_away.goals
            then v_fixture.home_user_id else v_fixture.away_user_id end;
        elsif v_breaker = 'MOST_ASSISTS' and v_home.assists <> v_away.assists then
          v_winner := case when v_home.assists > v_away.assists
            then v_fixture.home_user_id else v_fixture.away_user_id end;
        elsif v_breaker = 'HIGHER_SEED' then
          select entry.seed into v_home_seed from public.cup_entries entry
          where entry.cup_id = v_fixture.cup_id and entry.user_id = v_fixture.home_user_id;
          select entry.seed into v_away_seed from public.cup_entries entry
          where entry.cup_id = v_fixture.cup_id and entry.user_id = v_fixture.away_user_id;
          v_winner := case when v_home_seed < v_away_seed
            then v_fixture.home_user_id else v_fixture.away_user_id end;
        end if;

        if v_winner is not null then
          v_resolution := v_breaker;
          exit;
        end if;
      end loop;
    end if;

    if v_winner is null then
      raise exception 'Cup fixture % could not be resolved', v_fixture.id;
    end if;

    v_loser := case when v_winner = v_fixture.home_user_id
      then v_fixture.away_user_id else v_fixture.home_user_id end;

    update public.cup_fixtures fixture
    set home_score = v_home.total_score,
        away_score = v_away.total_score,
        winner_user_id = v_winner,
        status = 'COMPLETED',
        resolution = v_resolution,
        finished_at = pg_catalog.now()
    where fixture.id = v_fixture.id;

    update public.cup_entries entry
    set status = 'ELIMINATED', eliminated_round = v_fixture.round_number
    where entry.cup_id = v_fixture.cup_id and entry.user_id = v_loser;

    insert into public.cup_audit_log (cup_id, league_id, action, details)
    values (
      v_fixture.cup_id, v_fixture.league_id, 'FIXTURE_FINALIZED',
      jsonb_build_object(
        'fixture_id', v_fixture.id,
        'gameweek', p_gameweek,
        'home_score', v_home.total_score,
        'away_score', v_away.total_score,
        'winner_user_id', v_winner,
        'resolution', v_resolution
      )
    );
    v_updated := v_updated + 1;
  end loop;

  for v_round in
    select round.*
    from public.cup_rounds round
    join public.cups cup on cup.id = round.cup_id
    where round.gameweek = p_gameweek
      and round.status <> 'COMPLETED'
      and not exists (
        select 1 from public.cup_fixtures fixture
        where fixture.round_id = round.id
          and fixture.status not in ('COMPLETED', 'BYE')
      )
    order by round.cup_id, round.round_number
    for update of round
  loop
    update public.cup_rounds round
    set status = 'COMPLETED'
    where round.id = v_round.id;

    if v_round.round_number = (
      select cup.round_count from public.cups cup where cup.id = v_round.cup_id
    ) then
      select fixture.winner_user_id,
             case when fixture.winner_user_id = fixture.home_user_id
               then fixture.away_user_id else fixture.home_user_id end
      into v_winner, v_loser
      from public.cup_fixtures fixture
      where fixture.round_id = v_round.id
      order by fixture.match_number
      limit 1;

      update public.cups cup
      set status = 'COMPLETED', champion_user_id = v_winner,
          runner_up_user_id = v_loser, updated_at = pg_catalog.now()
      where cup.id = v_round.cup_id;
      update public.cup_entries entry
      set status = 'CHAMPION'
      where entry.cup_id = v_round.cup_id and entry.user_id = v_winner;
      insert into public.cup_audit_log (cup_id, league_id, action, details)
      values (
        v_round.cup_id, v_round.league_id, 'CUP_COMPLETED',
        jsonb_build_object('champion_user_id', v_winner, 'runner_up_user_id', v_loser)
      );
      v_completed_cups := v_completed_cups + 1;
    else
      select pg_catalog.array_agg(fixture.winner_user_id order by fixture.match_number)
      into v_winners
      from public.cup_fixtures fixture
      where fixture.round_id = v_round.id;

      select round.id into v_next_round_id
      from public.cup_rounds round
      where round.cup_id = v_round.cup_id
        and round.round_number = v_round.round_number + 1;

      for v_index in 1..(pg_catalog.cardinality(v_winners) / 2) loop
        insert into public.cup_fixtures (
          cup_id, league_id, round_id, round_number, match_number, gameweek,
          home_user_id, away_user_id, status
        ) values (
          v_round.cup_id, v_round.league_id, v_next_round_id,
          v_round.round_number + 1, v_index, p_gameweek + 1,
          v_winners[((v_index - 1) * 2) + 1],
          v_winners[((v_index - 1) * 2) + 2],
          'SCHEDULED'
        )
        on conflict (round_id, match_number) do nothing;
      end loop;

      update public.cups cup
      set status = 'LIVE', updated_at = pg_catalog.now()
      where cup.id = v_round.cup_id and cup.status = 'SCHEDULED';
    end if;
  end loop;

  return jsonb_build_object(
    'success', true,
    'gameweek', p_gameweek,
    'fixtures_finalized', v_updated,
    'cups_completed', v_completed_cups
  );
end;
$$;

revoke all on function public.finalize_cup_gameweek(integer)
  from public, anon, authenticated;
grant execute on function public.finalize_cup_gameweek(integer)
  to service_role;

create or replace function public.get_cup_fixture_board(p_league_id uuid)
returns table(
  cup_id uuid,
  cup_name text,
  cup_status text,
  round_id uuid,
  round_number integer,
  round_name text,
  gameweek integer,
  round_status text,
  fixture_id uuid,
  match_number integer,
  fixture_status text,
  home_user_id uuid,
  home_team_name text,
  home_score integer,
  home_fpl_points integer,
  home_defcon_points integer,
  away_user_id uuid,
  away_team_name text,
  away_score integer,
  away_fpl_points integer,
  away_defcon_points integer,
  winner_user_id uuid,
  resolution text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    cup.id,
    cup.name,
    cup.status,
    round.id,
    round.round_number,
    round.name,
    round.gameweek,
    round.status,
    fixture.id,
    fixture.match_number,
    fixture.status,
    fixture.home_user_id,
    coalesce(home_member.team_name, 'TBD'),
    case when fixture.status in ('COMPLETED', 'BYE')
      then coalesce(fixture.home_score, 0) else coalesce(home_live.total_score, 0) end,
    coalesce(home_live.fpl_points, 0),
    coalesce(home_live.defcon_points, 0),
    fixture.away_user_id,
    case when fixture.status = 'BYE' then 'BYE'
      else coalesce(away_member.team_name, 'TBD') end,
    case when fixture.status in ('COMPLETED', 'BYE')
      then coalesce(fixture.away_score, 0) else coalesce(away_live.total_score, 0) end,
    coalesce(away_live.fpl_points, 0),
    coalesce(away_live.defcon_points, 0),
    fixture.winner_user_id,
    fixture.resolution
  from public.cups cup
  join public.cup_rounds round on round.cup_id = cup.id
  left join public.cup_fixtures fixture on fixture.round_id = round.id
  left join public.league_members home_member
    on home_member.league_id = cup.league_id and home_member.user_id = fixture.home_user_id
  left join public.league_members away_member
    on away_member.league_id = cup.league_id and away_member.user_id = fixture.away_user_id
  left join lateral public.get_cup_manager_gameweek_score(
    cup.league_id, fixture.home_user_id, round.gameweek
  ) home_live on fixture.home_user_id is not null
  left join lateral public.get_cup_manager_gameweek_score(
    cup.league_id, fixture.away_user_id, round.gameweek
  ) away_live on fixture.away_user_id is not null
  where cup.league_id = p_league_id
    and exists (
      select 1 from public.league_members viewer
      where viewer.league_id = p_league_id and viewer.user_id = auth.uid()
    )
  order by cup.created_at desc, round.round_number, fixture.match_number;
$$;

revoke all on function public.get_cup_fixture_board(uuid) from public, anon;
grant execute on function public.get_cup_fixture_board(uuid)
  to authenticated, service_role;

comment on table public.cups is
  'League-scoped custom cup definitions. V1 supports secure single-knockout competitions.';
comment on function public.create_single_knockout_cup(uuid, text, integer, uuid[], text[]) is
  'Atomically snapshots participants, schedules rounds, draws opening fixtures and assigns byes.';
comment on function public.finalize_cup_gameweek(integer) is
  'Finalizes scheduled cup fixtures from effective Gameweek lineups and advances winners exactly once.';
