-- Server-owned gameweek lineup snapshots, deadline locking and repeat-safe autosubs.

create table if not exists public.gameweek_lineup_snapshots (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  gameweek integer not null check (gameweek between 1 and 38),
  deadline_at timestamptz not null,
  starting_player_ids integer[] not null,
  bench_player_ids integer[] not null,
  effective_starting_player_ids integer[] not null,
  effective_bench_player_ids integer[] not null,
  status text not null default 'LOCKED' check (status in ('LOCKED', 'PROCESSED', 'CORRECTED')),
  captured_at timestamptz not null default now(),
  processed_at timestamptz,
  corrected_at timestamptz,
  corrected_by uuid references auth.users(id),
  correction_reason text,
  unique (league_id, user_id, gameweek)
);

create index if not exists gameweek_lineup_snapshots_lookup_idx
  on public.gameweek_lineup_snapshots(league_id, gameweek, user_id);

create table if not exists public.gameweek_autosub_audit (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references public.gameweek_lineup_snapshots(id) on delete cascade,
  league_id uuid not null references public.leagues(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  gameweek integer not null,
  action_type text not null check (action_type in ('SWAP', 'SKIPPED', 'CORRECTION')),
  subbed_out_player_id integer references public.players(id),
  subbed_in_player_id integer references public.players(id),
  bench_priority integer,
  reason_code text not null,
  explanation text not null,
  created_at timestamptz not null default now()
);

create index if not exists gameweek_autosub_audit_lookup_idx
  on public.gameweek_autosub_audit(league_id, gameweek, user_id, created_at);

alter table public.gameweek_lineup_snapshots enable row level security;
alter table public.gameweek_autosub_audit enable row level security;

drop policy if exists "Managers and commissioners can view gameweek lineups" on public.gameweek_lineup_snapshots;
create policy "Managers and commissioners can view gameweek lineups"
  on public.gameweek_lineup_snapshots for select to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.leagues l
      where l.id = gameweek_lineup_snapshots.league_id
        and l.commissioner_id = auth.uid()
    )
  );

drop policy if exists "Managers and commissioners can view autosub audit" on public.gameweek_autosub_audit;
create policy "Managers and commissioners can view autosub audit"
  on public.gameweek_autosub_audit for select to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.leagues l
      where l.id = gameweek_autosub_audit.league_id
        and l.commissioner_id = auth.uid()
    )
  );

create or replace function public.is_legal_starting_lineup(p_player_ids integer[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select cardinality(coalesce(p_player_ids, array[]::integer[])) = 11
    and count(distinct submitted.player_id) = 11
    and count(*) filter (where upper(p.element_type::text) in ('GKP', 'GK', '1')) = 1
    and count(*) filter (where upper(p.element_type::text) in ('DEF', '2')) between 3 and 5
    and count(*) filter (where upper(p.element_type::text) in ('MID', '3')) between 2 and 5
    and count(*) filter (where upper(p.element_type::text) in ('FWD', '4')) between 1 and 3
  from unnest(coalesce(p_player_ids, array[]::integer[])) submitted(player_id)
  join public.players p on p.id = submitted.player_id;
$$;

create or replace function public.refresh_league_gameweek_schedule()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  insert into public.league_gameweeks (
    league_id, gameweek, gw_deadline, waiver_deadline,
    is_current, is_finished, status, waiver_deadline_time
  )
  select
    l.id,
    g.gameweek_number,
    g.fpl_deadline_time,
    g.fpl_deadline_time - interval '24 hours',
    coalesce(g.is_current, false),
    coalesce(g.is_finished, false),
    case
      when coalesce(g.is_finished, false) then 'FINISHED'
      when pg_catalog.now() >= g.fpl_deadline_time then 'IN_PLAY'
      else 'WAIVERS_OPEN'
    end,
    g.fpl_deadline_time - interval '24 hours'
  from public.leagues l
  cross join public.gameweeks g
  where exists (
    select 1 from public.rosters r where r.league_id = l.id
  )
  on conflict (league_id, gameweek) do update
  set gw_deadline = excluded.gw_deadline,
      waiver_deadline = excluded.waiver_deadline,
      waiver_deadline_time = excluded.waiver_deadline_time,
      is_current = excluded.is_current,
      is_finished = excluded.is_finished,
      status = case
        when excluded.is_finished then 'FINISHED'
        when pg_catalog.now() >= excluded.gw_deadline then 'IN_PLAY'
        when public.league_gameweeks.status in ('FINISHED', 'IN_PLAY') then 'WAIVERS_OPEN'
        else public.league_gameweeks.status
      end;

  get diagnostics v_count = row_count;
  return jsonb_build_object('success', true, 'gameweeks_synchronised', v_count);
end;
$$;

create or replace function public.capture_due_gameweek_lineups(p_gameweek integer default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  perform public.refresh_league_gameweek_schedule();

  insert into public.gameweek_lineup_snapshots (
    league_id, user_id, gameweek, deadline_at,
    starting_player_ids, bench_player_ids,
    effective_starting_player_ids, effective_bench_player_ids
  )
  select
    r.league_id,
    r.user_id,
    lg.gameweek,
    lg.gw_deadline,
    array_agg(r.player_id order by r.player_id) filter (where r.is_starting),
    array_agg(r.player_id order by r.bench_order nulls last, r.player_id) filter (where not r.is_starting),
    array_agg(r.player_id order by r.player_id) filter (where r.is_starting),
    array_agg(r.player_id order by r.bench_order nulls last, r.player_id) filter (where not r.is_starting)
  from public.rosters r
  join public.league_gameweeks lg
    on lg.league_id = r.league_id
   and (p_gameweek is null or lg.gameweek = p_gameweek)
  where lg.gw_deadline <= pg_catalog.now()
  group by r.league_id, r.user_id, lg.gameweek, lg.gw_deadline
  having count(*) = 15
     and count(*) filter (where r.is_starting) = 11
     and count(*) filter (where not r.is_starting) = 4
  on conflict (league_id, user_id, gameweek) do nothing;

  get diagnostics v_count = row_count;
  return jsonb_build_object('success', true, 'snapshots_created', v_count);
end;
$$;

create or replace function public.process_gameweek_autosubs(
  p_league_id uuid,
  p_gameweek integer,
  p_force boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_snapshot record;
  v_effective integer[];
  v_candidate integer[];
  v_starting_gk integer;
  v_bench_gk integer;
  v_bench_player integer;
  v_bench_priority integer;
  v_absent_starter integer;
  v_swap_count integer := 0;
  v_skipped_count integer := 0;
  v_processed_count integer := 0;
  v_gameweek_finished boolean;
begin
  if auth.uid() is not null
     and not exists (
       select 1 from public.leagues l
       where l.id = p_league_id and l.commissioner_id = auth.uid()
     ) then
    return jsonb_build_object('success', false, 'error', 'COMMISSIONER_REQUIRED');
  end if;

  select coalesce(g.is_finished, false)
  into v_gameweek_finished
  from public.gameweeks g
  where g.gameweek_number = p_gameweek;

  if not coalesce(v_gameweek_finished, false) and not p_force then
    return jsonb_build_object('success', false, 'error', 'GAMEWEEK_IN_PROGRESS');
  end if;

  perform public.capture_due_gameweek_lineups(p_gameweek);

  for v_snapshot in
    select *
    from public.gameweek_lineup_snapshots s
    where s.league_id = p_league_id
      and s.gameweek = p_gameweek
      and s.status = 'LOCKED'
    for update
  loop
    v_effective := v_snapshot.starting_player_ids;

    select submitted.player_id into v_starting_gk
    from unnest(v_snapshot.starting_player_ids) submitted(player_id)
    join public.players p on p.id = submitted.player_id
    where upper(p.element_type::text) in ('GKP', 'GK', '1')
    limit 1;

    select submitted.player_id into v_bench_gk
    from unnest(v_snapshot.bench_player_ids) submitted(player_id)
    join public.players p on p.id = submitted.player_id
    where upper(p.element_type::text) in ('GKP', 'GK', '1')
    limit 1;

    if coalesce((select s.minutes from public.player_gameweek_stats s where s.player_id = v_starting_gk and s.gameweek = p_gameweek), 0) = 0 then
      if coalesce((select s.minutes from public.player_gameweek_stats s where s.player_id = v_bench_gk and s.gameweek = p_gameweek), 0) > 0 then
        v_effective := array_replace(v_effective, v_starting_gk, v_bench_gk);
        insert into public.gameweek_autosub_audit (
          snapshot_id, league_id, user_id, gameweek, action_type,
          subbed_out_player_id, subbed_in_player_id, bench_priority,
          reason_code, explanation
        ) values (
          v_snapshot.id, p_league_id, v_snapshot.user_id, p_gameweek, 'SWAP',
          v_starting_gk, v_bench_gk, 0,
          'GOALKEEPER_DID_NOT_PLAY',
          'The starting goalkeeper played 0 minutes, so the substitute goalkeeper was used.'
        );
        v_swap_count := v_swap_count + 1;
      else
        insert into public.gameweek_autosub_audit (
          snapshot_id, league_id, user_id, gameweek, action_type,
          subbed_out_player_id, bench_priority, reason_code, explanation
        ) values (
          v_snapshot.id, p_league_id, v_snapshot.user_id, p_gameweek, 'SKIPPED',
          v_starting_gk, 0, 'NO_GOALKEEPER_REPLACEMENT',
          'The starting goalkeeper played 0 minutes, but the substitute goalkeeper also did not play.'
        );
        v_skipped_count := v_skipped_count + 1;
      end if;
    end if;

    for v_bench_player, v_bench_priority in
      select submitted.player_id, (submitted.ordinality - 1)::integer
      from unnest(v_snapshot.bench_player_ids) with ordinality submitted(player_id, ordinality)
      join public.players p on p.id = submitted.player_id
      where upper(p.element_type::text) not in ('GKP', 'GK', '1')
        and coalesce((
          select s.minutes from public.player_gameweek_stats s
          where s.player_id = submitted.player_id and s.gameweek = p_gameweek
        ), 0) > 0
      order by submitted.ordinality
    loop
      v_absent_starter := null;

      for v_absent_starter in
        select effective.player_id
        from unnest(v_effective) with ordinality effective(player_id, ordinality)
        join public.players p on p.id = effective.player_id
        where upper(p.element_type::text) not in ('GKP', 'GK', '1')
          and coalesce((
            select s.minutes from public.player_gameweek_stats s
            where s.player_id = effective.player_id and s.gameweek = p_gameweek
          ), 0) = 0
        order by effective.ordinality
      loop
        v_candidate := array_replace(v_effective, v_absent_starter, v_bench_player);
        if public.is_legal_starting_lineup(v_candidate) then
          v_effective := v_candidate;
          insert into public.gameweek_autosub_audit (
            snapshot_id, league_id, user_id, gameweek, action_type,
            subbed_out_player_id, subbed_in_player_id, bench_priority,
            reason_code, explanation
          ) values (
            v_snapshot.id, p_league_id, v_snapshot.user_id, p_gameweek, 'SWAP',
            v_absent_starter, v_bench_player, v_bench_priority,
            'OUTFIELD_PLAYER_DID_NOT_PLAY',
            'A starting outfield player played 0 minutes. The highest-priority eligible substitute was used while preserving a legal formation.'
          );
          v_swap_count := v_swap_count + 1;
          exit;
        end if;
      end loop;
    end loop;

    for v_absent_starter in
      select effective.player_id
      from unnest(v_effective) effective(player_id)
      join public.players p on p.id = effective.player_id
      where upper(p.element_type::text) not in ('GKP', 'GK', '1')
        and coalesce((
          select s.minutes from public.player_gameweek_stats s
          where s.player_id = effective.player_id and s.gameweek = p_gameweek
        ), 0) = 0
    loop
      insert into public.gameweek_autosub_audit (
        snapshot_id, league_id, user_id, gameweek, action_type,
        subbed_out_player_id, reason_code, explanation
      ) values (
        v_snapshot.id, p_league_id, v_snapshot.user_id, p_gameweek, 'SKIPPED',
        v_absent_starter, 'NO_ELIGIBLE_SUBSTITUTE',
        'No playing substitute could replace this player without breaking the formation rules.'
      );
      v_skipped_count := v_skipped_count + 1;
    end loop;

    update public.gameweek_lineup_snapshots
    set effective_starting_player_ids = v_effective,
        effective_bench_player_ids = v_snapshot.bench_player_ids,
        status = 'PROCESSED',
        processed_at = pg_catalog.now()
    where id = v_snapshot.id;

    v_processed_count := v_processed_count + 1;
  end loop;

  return jsonb_build_object(
    'success', true,
    'league_id', p_league_id,
    'gameweek', p_gameweek,
    'lineups_processed', v_processed_count,
    'swaps', v_swap_count,
    'unresolved_absences', v_skipped_count
  );
end;
$$;

create or replace function public.process_due_gameweek_autosubs(p_gameweek integer default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league record;
  v_gameweek record;
  v_result jsonb;
  v_processed integer := 0;
begin
  perform public.refresh_league_gameweek_schedule();
  perform public.capture_due_gameweek_lineups(p_gameweek);

  for v_gameweek in
    select g.gameweek_number
    from public.gameweeks g
    where coalesce(g.is_finished, false)
      and (p_gameweek is null or g.gameweek_number = p_gameweek)
  loop
    for v_league in
      select distinct s.league_id
      from public.gameweek_lineup_snapshots s
      where s.gameweek = v_gameweek.gameweek_number and s.status = 'LOCKED'
    loop
      v_result := public.process_gameweek_autosubs(v_league.league_id, v_gameweek.gameweek_number, false);
      v_processed := v_processed + coalesce((v_result ->> 'lineups_processed')::integer, 0);
    end loop;
  end loop;

  return jsonb_build_object('success', true, 'lineups_processed', v_processed);
end;
$$;

-- Preserve the existing Edge Function RPC signature, but stop mutating the live roster.
create or replace function public.process_auto_subs(p_gameweek integer)
returns table(
  league_id uuid,
  roster_id uuid,
  subbed_out_player_id integer,
  subbed_in_player_id integer,
  sub_reason text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.process_due_gameweek_autosubs(p_gameweek);
  return query
  select
    a.league_id,
    r.id,
    a.subbed_out_player_id,
    a.subbed_in_player_id,
    a.explanation
  from public.gameweek_autosub_audit a
  left join public.rosters r
    on r.league_id = a.league_id
   and r.user_id = a.user_id
   and r.player_id = a.subbed_out_player_id
  where a.gameweek = p_gameweek and a.action_type = 'SWAP';
end;
$$;

create or replace function public.commissioner_correct_gameweek_lineup(
  p_league_id uuid,
  p_user_id uuid,
  p_gameweek integer,
  p_effective_starting_player_ids integer[],
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_snapshot public.gameweek_lineup_snapshots%rowtype;
begin
  if auth.uid() is null or not exists (
    select 1 from public.leagues l
    where l.id = p_league_id and l.commissioner_id = auth.uid()
  ) then
    return jsonb_build_object('success', false, 'error', 'COMMISSIONER_REQUIRED');
  end if;

  if nullif(trim(coalesce(p_reason, '')), '') is null then
    return jsonb_build_object('success', false, 'error', 'CORRECTION_REASON_REQUIRED');
  end if;

  select * into v_snapshot
  from public.gameweek_lineup_snapshots s
  where s.league_id = p_league_id and s.user_id = p_user_id and s.gameweek = p_gameweek
  for update;

  if not found then
    return jsonb_build_object('success', false, 'error', 'SNAPSHOT_NOT_FOUND');
  end if;

  if not public.is_legal_starting_lineup(p_effective_starting_player_ids)
     or exists (
       select 1 from unnest(p_effective_starting_player_ids) submitted(player_id)
       where not (submitted.player_id = any(v_snapshot.starting_player_ids || v_snapshot.bench_player_ids))
     ) then
    return jsonb_build_object('success', false, 'error', 'INVALID_CORRECTED_LINEUP');
  end if;

  update public.gameweek_lineup_snapshots
  set effective_starting_player_ids = p_effective_starting_player_ids,
      status = 'CORRECTED',
      corrected_at = pg_catalog.now(),
      corrected_by = auth.uid(),
      correction_reason = trim(p_reason)
  where id = v_snapshot.id;

  insert into public.gameweek_autosub_audit (
    snapshot_id, league_id, user_id, gameweek, action_type,
    reason_code, explanation
  ) values (
    v_snapshot.id, p_league_id, p_user_id, p_gameweek, 'CORRECTION',
    'COMMISSIONER_CORRECTION', trim(p_reason)
  );

  return jsonb_build_object('success', true, 'snapshot_id', v_snapshot.id);
end;
$$;

-- Wrap the existing manager save function with an authoritative deadline check.
do $$
begin
  if to_regprocedure('public.save_manager_lineup_unlocked(uuid,integer[],integer[])') is null then
    alter function public.save_manager_lineup(uuid, integer[], integer[])
      rename to save_manager_lineup_unlocked;
  end if;
end;
$$;

create or replace function public.save_manager_lineup(
  p_league_id uuid,
  p_starting_player_ids integer[],
  p_bench_player_ids integer[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_locked_gameweek integer;
begin
  select g.gameweek_number into v_locked_gameweek
  from public.gameweeks g
  where g.fpl_deadline_time <= pg_catalog.now()
    and not coalesce(g.is_finished, false)
  order by g.gameweek_number desc
  limit 1;

  if v_locked_gameweek is not null then
    perform public.capture_due_gameweek_lineups(v_locked_gameweek);
    return jsonb_build_object(
      'success', false,
      'error', 'LINEUP_LOCKED',
      'gameweek', v_locked_gameweek
    );
  end if;

  return public.save_manager_lineup_unlocked(
    p_league_id,
    p_starting_player_ids,
    p_bench_player_ids
  );
end;
$$;

create or replace function public.run_gameweek_lineup_lifecycle()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_schedule jsonb;
  v_snapshots jsonb;
  v_autosubs jsonb;
begin
  v_schedule := public.refresh_league_gameweek_schedule();
  v_snapshots := public.capture_due_gameweek_lineups(null);
  v_autosubs := public.process_due_gameweek_autosubs(null);
  return jsonb_build_object(
    'success', true,
    'schedule', v_schedule,
    'snapshots', v_snapshots,
    'autosubs', v_autosubs
  );
end;
$$;

-- Repair the existing transition worker to use the real league_gameweeks schema.
create or replace function public.process_gameweek_state_transitions()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  return public.run_gameweek_lineup_lifecycle();
end;
$$;

-- The previous scheduler embedded a revoked legacy JWT. Read a dedicated cron
-- secret from Vault instead; the value is provisioned separately from source control.
create or replace function public.trigger_live_stats_sync()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_gw integer;
  v_cron_secret text;
  v_request_id bigint;
begin
  select g.gameweek_number into v_current_gw
  from public.gameweeks g
  where coalesce(g.is_current, false)
  order by g.gameweek_number desc
  limit 1;

  if v_current_gw is null then
    select g.gameweek_number into v_current_gw
    from public.gameweeks g
    where not coalesce(g.is_finished, false)
    order by g.fpl_deadline_time
    limit 1;
  end if;

  v_current_gw := coalesce(v_current_gw, 1);

  select s.decrypted_secret into v_cron_secret
  from vault.decrypted_secrets s
  where s.name = 'live_stats_cron_secret'
  limit 1;

  if v_cron_secret is null then
    raise warning 'live_stats_cron_secret is not configured; live stats sync skipped';
    return;
  end if;

  select net.http_get(
    url := 'https://fnysbiwhwcqqqdwvhkau.supabase.co/functions/v1/sync-live-stats?gameweek=' || v_current_gw,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', v_cron_secret
    )
  ) into v_request_id;
end;
$$;

revoke all on function public.save_manager_lineup_unlocked(uuid, integer[], integer[]) from public, anon, authenticated;
revoke all on function public.refresh_league_gameweek_schedule() from public, anon, authenticated;
revoke all on function public.capture_due_gameweek_lineups(integer) from public, anon;
revoke all on function public.process_due_gameweek_autosubs(integer) from public, anon, authenticated;
revoke all on function public.process_auto_subs(integer) from public, anon, authenticated;
revoke all on function public.run_gameweek_lineup_lifecycle() from public, anon, authenticated;
revoke all on function public.trigger_live_stats_sync() from public, anon, authenticated;
revoke all on function public.process_gameweek_state_transitions() from public, anon, authenticated;
revoke all on function public.is_legal_starting_lineup(integer[]) from public, anon;

grant execute on function public.save_manager_lineup(uuid, integer[], integer[]) to authenticated;
grant execute on function public.capture_due_gameweek_lineups(integer) to authenticated, service_role;
grant execute on function public.process_gameweek_autosubs(uuid, integer, boolean) to authenticated, service_role;
grant execute on function public.commissioner_correct_gameweek_lineup(uuid, uuid, integer, integer[], text) to authenticated;
grant execute on function public.process_auto_subs(integer) to service_role;
grant execute on function public.process_due_gameweek_autosubs(integer) to service_role;
grant execute on function public.refresh_league_gameweek_schedule() to service_role;
grant execute on function public.run_gameweek_lineup_lifecycle() to service_role;
grant execute on function public.is_legal_starting_lineup(integer[]) to authenticated, service_role;
grant select on public.gameweek_lineup_snapshots to authenticated;
grant select on public.gameweek_autosub_audit to authenticated;

do $$
declare
  v_job_id bigint;
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    select jobid into v_job_id from cron.job where jobname = 'gameweek-lineup-lifecycle';
    if v_job_id is not null then
      perform cron.unschedule(v_job_id);
    end if;
    perform cron.schedule(
      'gameweek-lineup-lifecycle',
      '* * * * *',
      'select public.run_gameweek_lineup_lifecycle();'
    );
  end if;
end;
$$;

comment on table public.gameweek_lineup_snapshots is
  'Immutable deadline lineup plus separately processed effective gameweek lineup.';
comment on function public.process_gameweek_autosubs(uuid, integer, boolean) is
  'Processes goalkeeper and priority-ordered outfield autosubs without mutating the manager current roster.';
